define audio.ambient_city = "audio/ambient-city.ogg"
define audio.ambient_club = "audio/ambient-club.ogg"
define audio.backdoor_close = "audio/backdoor-close.ogg"
define audio.backdoor_open = "audio/backdoor-open.ogg"
define audio.navcomp = "audio/navcomp.ogg"
define audio.whiskey_ice = "audio/whiskey-ice.ogg"
define audio.whiskey_pour = "audio/whiskey-pour.ogg"
define audio.whiskey_toast = "audio/whiskey-toast.ogg"