# image cg_elonmusk_liftoff = "cgs/elonmusk/liftoff.webp"
image cg_whiskeynight = "cg/CG_Whiskey.webp"
image cg_co_laugh = "cg/CG_Coop_Laugh.webp"
image cg_co_neutral = "cg/CG_Coop_Neutral.webp"
image cg_co_smile = "cg/CG_Coop_Smile.webp"
image cg_ri_neutral = "cg/CG_Rival_Neutral.webp"
image cg_ri_noeris = "cg/CG_Rival_NoEris.webp"
image cg_ri_smile = "cg/CG_Rival_Smile.webp"