label A1_07r:
    scene bg_black with Dissolve(0.5)
    "After that, the days just kept... passing."
    "Sounds like a bit of a no brainer, but I guess it just goes to show how much energy I've put into that stupid bet with Eris."
    "With that whole business behind us, all I've got is just the regular old work at Arcady. God knows there hasn't been a sudden, new customer boom."
    "It's the same as it always was, except now time's getting all funky in all-too familiar ways."
    "On the one hand, the hours stretch thinner and longer and stickier each passing night, like sickly sweet tachyon toffee. It's not that anything happens -- it just takes forever not to."
    "An impossible amount of tired, trite, samey-same boring irrelevant shit squeezing tighter and tighter into what the clock keeps insisting is the same amount of time."
    "And at the same time, unless I'm paying attention, it feels like life's passing me by in a blur."
    "I come to work in the evening, spend what feels like an age and a half waiting tables and cleaning the floor and listening to Eris' singing and wondering how much of it is recorded, then bam, it's morning, and in retrospect, all that time implodes into one instant 'nothing got done.'"
    "I get back home feeling drained like I've done my work five times, but without the benefits of having actually {i}accomplished{/i} any of it."
    "Either something's gone terribly wrong with some high-energy quantum whatchamacallit at the nearest university--"
    "--or I'm sinking into a routine again."
    "And much as I'm all for the cohesion of the time-space continuum, I really don't know which one I'd rather have."
    play audio [backdoor_open, backdoor_close]
    scene bg_back_alley with Dissolve(0.5)
    roman "There goes another night..."
    "With my shift being over, I say goodbye to Parker, pick my jacket off of the hanger and leave through the front door, waving noncommittally to that one guy with the pink bangs who leaves big tips."
    "The air's warm and moist outside. At this hour, the sounds of the city aren't quite muted, but dampened."
    "About halfway back home, my knees, which have seen better days as it was, begin whining about the evening's standing around and carrying plates. Those assholes at table 6 did go a little bit nuts with those fries."
    "If only for the sake of a change of pace, maybe, I decide to head for the nearest bus station."
    "Minding one at the end of the street, I sit down, stretch, and glance aside at the timetable to see when the next one's arriving."
    "Naturally, it's all dust and scratches and those annoying little white bars that tell you the one you're seeing is probably twenty years out of date and pull up your display if you want to know when the bus is coming."
    "I reach for my pocket to take my phone out."
    roman "..."
    roman "...Huh?"
    roman "What the--"
    "Fiddling around in my pants pocket, then my jacket pocket, for a short minute produces little more than air, lint, and a ball of mush that might've once been someone's calling card Ill-fated to the laundry."
    roman "....Shit."
    "Tracing my steps back to the beginning of my shift, I must've left it inside when Eris started on this one song, and I pulled it out to check which one it was and--"
    "Well, at least it should still be at the staff only area, if I remember correctly. I mean, Parker's probably got better things to do than steal his employees' electronics and Eris wouldn't be caught dead with any device over six-months old."
    "Sighing deeply, I turn back towards the club."
    play audio [backdoor_open, backdoor_close]
    scene bg_club_2_after_work with Dissolve(0.5) 
    "Parker's nowhere to be seen. Sneaky old bastard moves fast."
    "I make my way towards the staff area, quickly spotting my phone on the table. As I'm about to leave, my eyes adjust to the dim light and my attention shifts towards a sight...as unexpected as it is unfortunately familiar."
    show eris p2 e5 at centered
    "Sitting at the table with a strained, focused, almost desperate expression is Eris. Her shoulders are slumped uncomfortably, and from the wrinkles under her eyes one could only imagine that she's been here a while."
    "Her lips are trembling in frustration. Her foot taps absentmindedly on the ground in an uneven pace."
    "From the way her eyes are fixed on thin air and how she's waving her hands, this is one hell of an intense web surfing session she's doing."
    "I pull out my phone to check. Through the display, the myriad AR windows and screen floating stilly in the air in front of her become clear."
    roman "Online shopping while at work? What's the matter, kicked out of your place?"

    if scene_5_cooperation:
        call A1_07r_c
    else:
        call A1_07r_r

    show eris p2 e7 at centered
    eris "So, remember how my last plan failed because it turned out Arcady doesn't have the electronic infrastructure to pull it off?"
    roman "Your... plan?"
    eris "For the bet we had a while back!"
    roman "Oh. Right. That plan."
    "Part of me's rolling my eyes now, sorry she's ever brought that up. I just wanted to forget about that whole mess."
    "It's like when you blurt out something at a party that turns out to be way dumber than you'd imagined and everyone laughs at you--they'd probably forget that the next time they have a bowel movement, but you're going to come back to that and feel like an idiot every too-quiet sleepless night for the next twenty years and wish you'd shut it."
    "Another part of me, though, leaps to attention. Sure, it was a disaster, but if I'm being honest here it {i}was{/i} the last interesting thing to happen around here."
    "Eris continues."
    eris "So anyway, I've been thinking: we couldn't make it work back then, but it's still a great idea on principle, right?"
    "I chuckle uncomfortably."
    roman "Don't ask questions you don't really want me to answer."
    eris p2 e5 "Come on, Roman! Quit it! The bet's over, this is no longer a competition! I really want what's best for Arcady, okay?"
    roman "Fine, but I still don't like your idea. What're you gonna do about it?"
    eris "Okay. Then just listen to it, alright?"
    roman "Go on."
    eris p1 e1 "So as I was saying, {i}I{/i} still think my idea was good. And since what stopped it from working was infrastructure issues--"
    eris "--I figured I'll do this business a favor by improving the infrastructure."
    eris p1 e6 "That's not nearly as unrealistic, right? It doesn't have to happen fast and it doesn't have to be anything grandiose."
    eris p2 e7 "Honestly, with what this place has at the moment, basically anything would be an improvement, right?"
    eris "I mean, obviously, I'd rather it be a more substantial one--"
    roman "I'm feeling like there's a huge 'but' out there somewhere that's waiting to pounce on me sooner or later."
    roman "Mind just cutting straight to it?"
    "Eris's face sours."
    eris p2 e5 "Fine, let's be all bitter and blunt:"
    eris "This shit's hard. There, I said it."
    eris "This shit is really fucking hard, and I had no idea what I was getting into."
    eris p3 e8 "I'm in {i}way{/i} over my head here, Roman. I figured since I've shopped for electronics so many times in the past this'll be a breeze, but it turns out that getting and installing all that really serious hardware is a completely different matter."
    roman "You don't say."
    eris p2 e5 "Don't give me that smug shit, I'm pissed off enough as it is. I've been bashing my head against that stuff for {i}hours{/i} now and I can't even make heads or tails out of anything. I feel like I'm going nuts. I don't even know what half those specifications are {i}for{/i}."
    eris "Like, what in the world is a 'PPS' and why can't we get one? What's the difference between the C and E series?"
    eris "What's that BPT everyone's talking about? Why do half the forums tell me if I get the F2600 with the DDSX I'll burn this place to the ground, but the other half tells me if I don't everything will go to shit and it won't render?"
    eris "What connects to VK? Why doesn't it say anywhere how to put all those different systems together?"
    eris p3 e8 "It's all Chinese to me. Even the parts that {i}aren't{/i} in Chinese. And I {i}read{/i} Chinese, for fuck's sake!"
    "She crosses her arms in annoyance, and I have an ominous feeling that I know exactly where she's going with it."
    eris "It's like... I'm neck deep in all that stuff, I haven't logged out since my shift ended, it's been {i}so{/i} many hours now and I'm dying to go to sleep but, like, I can't stop now, you know?"
    eris "I {i}hate{/i} leaving stuff like that unfinished. I don't want to give up on this, I know it's possible. I'm not overreaching this time, I'm just out of my professional comfort zone."
    eris p1 e6 "But {i}you{/i} aren't, right?"
    eris "Right?!"
    "She forces a smile to her face that looks equal parts hopeful and pained."
    roman "Well, I mean, waiting hasn't exactly been my childhood dream, but if it's in a place like that--"
    eris p2 e5 "You {i}know{/i} that's not what I'm talking about, Roman!"
    eris "I've worked with you long enough in ARTech. I know what you did there, and I know that you were good at it."
    eris "That stuff I've been struggling with for the past hours? It's gonna be a piece of cake for you. You talk that language. You know the names of all those parts. You know how to build connections."
    eris p1 e6 "If we work together at this, I know we could end up improving Arcady so that everyone'll benefit. I'll help you in any way I can, I just need you to provide your technical expertise."
    eris p1 e1 "I won't force you if you say 'no'. I swear. No games, no nothing. I'm not your boss anymore."
    eris "This is just me asking you for a favor. That's all."
    "Her eyes sparkle pleadingly."
    "Now comes my turn to cross my arms and rub my temples and go through all those all too intentional involuntary motions people do to make sure that everyone knows what an internal struggle they're going through while they try to figure things out."
    roman "There's a reason that I left ARTech."
    eris p3 e8 "I know, I know. I'm not asking you to go back there or anything, right? This'll be a simple job for you. You could do it in minutes."
    roman "Really? Minutes?"
    eris p1 e1 "Well, maybe not {i}minutes{/i}, minutes--maybe hours... then, uh, maybe a few more hours once we've actually gotten all the equipment we need and start tearing things down where we need them--"
    eris "--but the point is that it won't be that hard you for you, right? You did this all the time."
    roman "Yeah! Until I got tired of it!"
    show eris p3 e8 at centered
    "Eris's shoulders slump. All that fake energy begins to slowly evaporate off her face, once again leaving me seeing the bags under the eyes and the frustrated wrinkles."
    "What am I doing?"
    "I got so mopey before over there being nothing do--over everything being the same--"
    "And now there's finally an opportunity to break that dreadful routine, I just... dismiss it?"
    "On the other hand, it's not like I'm lying here."
    "Eris, of all people, should know on what terms I left ARTech, and why."
    "She was the one who tried to stop me. More than anyone."
    "Which, by itself, makes the whole situation feel strange since a little, irrational bit of my mind keeps wondering whether this is some kind of scam--"
    "Some stupid, childish plan of hers to get me to suddenly realize that, actually, there's nothing I love in the world more than spending two hours straight down on my knees with my head shoved inside the ass of a mainframe, clutching a flashlight between my teeth and wondering who the fuck did it and what they could possibly have done to melt that connection like fudge."
    "That my destiny's been to do that for the rest of my life."
    "Eris bites on her lower lip, first in what looks like despair, then, slowly, anger."
    eris p2 e5 "Look, I'm not going to beg you, alright? If you don't want to, I'll do it myself."
    roman "Yeah? You would? Looking like that?"
    roman "Then what? You're going to send me home knowing I've left you here to wear yourself thin for the rest of the night, fiddling with an area you don't know the first thing about? Do you think you could willpower your way through a computer engineering degree in six hours?"
    roman "Get some sleep, watch some shows, then come back here tomorrow and look you in the eye?"
    roman "Look at you. You're a mess. Your makeup's running like Athens is safe from the Persians. I bet you haven't eaten since yesterday's lunch. What kind of asshole do you think I am?"
    eris p2 e7 "Don't ask questions you don't really want me to answer."
    "A silence hangs heavy and thick in the air as the sentence is let sink between us, like a whiskey pebble through..."
    "I dunno, a jello shot. Something way thicker than whiskey, in any case."
    roman "Okay, you got me there."
    roman "{i}That{/i} was kind of funny."
    roman "Look--"
    roman "I'm not promising anything."
    roman "Yet."
    roman "Let me take a look at what you've had in mind. Then, we'll see if it's doable."
    roman "One thing, though:"
    roman "I am {i}not{/i} going back to ARTech. This is final. It's not up for debate."
    roman "So don't bother."
    roman "Deal?"
    "Her little, tired smile widens almost imperceptibly."
    eris "Sure. Let's do this."
    show eris p2 e7 at transform_hide
    hide eris
    "Motioning for me to come closer and hold up my phone, Eris resumes waving her fingers and expands the screens that were floating in front of her face."
    "Product lists, reviews, forums, FAQs, Q & A's, intro videos."
    "It's like she's planning on opening a whole new club, made of computer parts, and building it in her garage."
    roman "So, the way I see it--and this could just be my opinion--we're going to need..."
    show bg_black with Dissolve(0.75)
    scene bg_club_2_during_work with Dissolve(0.75)
    "If nothing else, things get a lot more hectic from that day on."
    "The first stage's easy: just a couple nights of sitting around with Eris searching the web for affordable, energy and heat efficient bits of infrastructure that we could conceivably install by ourselves to get the kind of all-around upgrade she had in mind out of this."
    "The most tired I get around this part's my arm cramping up from having to hold up my phone at all times so I can see the AR windows she's viewing."
    "We get around that once she asks Parker for one of those comfy chairs, with armrests, so I can sorta awkwardly place my elbow on it and only get wrist cramps, instead."
    "At first, I'm worried we might not able to pay for some of the stuff that immediately popped to my mind once Eris started describing the sort of system overhaul she wanted, but then I found out two things:"
    "First, it really has been a while since I've looked around those computer part catalogues. Eris might not know the first thing about how to work with them but I'll give her that: she did do her homework fine."
    "It's kind of sickening how fast technology progresses. You have it in your mind that this one process's impossible to pull off at all without either getting a new radiator or shutting the whole system down every three hours so you won't liquify the customers."
    "Then Eris points me to this webstore, and they got this chip that does it and only needs to be turned off for cooling every {i}two{/i} hours. Assuming we don't want to shell it out for the cryotanks, which we don't."
    "Second: Eris actually offered to pay out of her own pocket for everything I thought was good, so I could go wild. At first I thought I'd show her for it and just order a truckload of fans or something, but, I mean, she {i}was{/i} pretty nice about it."
    "Might as well do fine by her, too."
    "The second stage starts once the orders we've made start arriving."
    show eris p1 e6 at centered
    eris "Everything going fine?"
    eris "Still down there, huh?"
    roman "Yeah. Just got to figure out how to get this panel open without breaking that part of the wall down. Parker's not gonna have it."
    roman "I guess I could bring over tools tomorrow, but I keep having this feeling like I'm missing something obvious and I'm going to feel like an idiot if I do that."
    roman "Just give me another half hour to think about this."
    eris "Okay, sure. I made some coffee if you're feeling like it--left your cup outside so we won't have another 'incident' with the cables, right?"
    roman "Right. Thanks."
    eris "Tell me if there's anything!"
    roman "Sure."
    show eris p1 e6 at transform_hide
    hide eris
    "Strictly speaking, Eris wants to help. It {i}is{/i} her idea."
    "In the great scheme of things, this is her passion project, and I'm the one who's just lending a hand."
    "But--"
    show eris p1 e1 at centered
    eris "Hey, Roman? I was thinking--what if we could go for the NG 2.0 after all instead of the 1.8? That way we could--"
    roman "Short this whole thing out."
    eris p1 e2 "Huh?"
    roman "We'll short all of this out. The whole club. That's what we could do."
    eris "Yeah, but what if we could--"
    roman "We can't."
    eris p3 e8 "Okay..."
    show eris p3 e8 at transform_hide
    hide eris
    "It's not that I mind it that she's involved. I wouldn't be doing this otherwise, and I don't mind the extra activity."
    "It's about how her involvement... manifests."
    "And what angers me the most is that I knew, very well, that this would happen."
    "Or at least, I had enough suspicions that I don't feel like I can free myself of responsibility and put it all on her on her at those times when--"
    show eris p2 e5 at centered
    eris "Roman? Are you done there?"
    roman "Just a moment, Eris. I got an order on table number six."
    eris "Okay, you go do that."
    roman "Great--"
    eris "Just, about the processor--"
    roman "...What?"
    eris "Well, I was thinking that maybe..."
    eris "You know what? You go ahead and finish with table six, then we talk about it. I'm going up in five minutes anyway, so it'll all work out."
    "Yeah, you go do that. You know, your job. Thanks for the permission to continue to do mine, by the way."
    show eris p2 e5 at transform_hide
    hide eris
    "I don't say that last part. It's on the top of my tongue, and unlike how it always used to do, now there's nothing that's really preventing me to."
    "Eris can't give me orders anymore, so as long as we keep this whole quiet enough that Parker doesn't mind..."
    "...I could just say 'no' to her face at any point and be done with it."
    "I could just refuse to help her."
    "And at some moments, I'm almost tempted to--"
    show eris p1 e6 at centered
    eris "Hi Roman! Just wanted to make sure."
    eris "We'll be finished with the emitters tonight, right?"
    eris "Like, there's no chance that we'll end up working halfway, then we need to go back home to sleep, then the customers arrive tomorrow night and it's all a mess..."
    roman "We?"
    roman "{i}I{/i} will be finished, yes. Thank you for your concern."
    roman "Now go back to the back area and do the drill thing. Remove the IE where we marked, place the HESes and leave them for me."
    eris p3 e8 "Oookay..."
    show eris p3 e8 at transform_hide
    hide eris
    "Jesus, I hate it when she's like that. I can't feel good with being mad at her this way."
    "The thing is, though, I know I should be. What she's doing is not right, and I'm not at fault for this."
    show bg_black with Dissolve(0.75)
    scene bg_back_alley with Dissolve(0.75)
    "The more this goes on, the more I get that uncomfortable, heavy feeling in the pit of my stomach that it's all building up towards something."
    "That the whole 'renovating the electrical infrastructure' is just Eris' newest, clumsiest way of trying to get at me for everything that's happened."
    roman "No matter what I do, I just can't seem to catch a break."
    show eris p1 e1 at centered
    play audio backdoor_open
    eris "Roman?"
    "Eris emerges sheepishly through the backdoor."
    "The sounds of the club leak out for just a moment, filling the dry air around us, then quiet down just as fast with the clang of it closing behind her."
    play audio backdoor_close
    "I take the cigarette out of my mouth to exhale. The feeling of emptiness in my chest feels so natural."
    "I don't even look her way. It feels like too much of commitment. She'll read in it stuff that's not there and hold me up to it."
    roman "What?"
    eris p3 e8 "Nothing, I just wanted to ask about the transmitters--"
    roman "Okay. Go on."
    eris p1 e1 "Hm?"
    roman "I said 'go on'. Let's not turn this into a friendly chat. You wanted to tell me what you need me to do again, right? Then say it."
    roman "I'll get to it right after my break. I'm still getting those, aren't I?"
    show eris p2 e5 at centered
    "I glance aside towards her. I think I've missed the exact moment where her expression all wrinkled into frustration, but it sure is the case right now."
    eris "Yes, you are."
    eris "You want me to come back later?"
    roman "That's a real question?"
    "Her nose goes red like a cherry. She bites on her lip like I've only ever seen her doing so many times in our way, way too-long history."
    eris p2 e5 "Yes! Yes, it is a real question!"
    eris "Jesus, why are you being like this? You don't owe me anything! I told you that before!"
    eris "If you don't want to help me, just say so?"
    "I can't help it. I can't contain myself, either."
    "I'm not feeling bad about this at all. If Eris gets to throw a tantrum at {i}me{/i} after all this time, I sure as hell am allowed to pay her back like it."
    roman "Really? I don't?"
    eris "No!"
    roman "Seriously? Because I'm pretty sure that's not really what you mean. Because you say that to me, knowing full well that I'm not going to say 'no' because I don't want you to go and {i}electrocute{/i} yourself trying to show me by doing this alone--or worse, burn this whole place to the ground--"
    roman "--and that way, you get to feel like the good guy in all of this, and you get to feel smug like this is all your work because you're running the show all over again. But..."
    roman "...You don't actually have a plan if I say 'no', do you? You don't have any idea what you'll do then. You'll pout and you'll call me names and you'll go on and on insinuating that you'll do this yourself and I'll stay behind, but you can't."
    roman "You never could, could you?"
    roman "So don't give me that crap, okay? I'm okay with doing all the work, and I'm even okay for doing it for you, while you sit back with all starry-eyed giving me orders."
    roman "Just don't give me that crap about us doing this 'together' like I want to do this. I don't."
    roman "So what is it?"
    show eris p3 e8 at centered
    "Eris' lips tremble."
    eris "Nothing. Forget about it."
    show eris p3 e8 at transform_hide
    hide eris
    "She turns to leave--"
    roman "Wait!"
    show eris p3 e8 at centered
    roman "Look, Eris, I'm sorry, it's just--"
    roman "--I don't know. This whole thing is just..."
    "I want to say something. I honestly do. I got so many things on my mind."
    "When I open my mouth, though, it's all gone. There's nothing."
    roman "What did you want?"
    "The silence is stifling. Smothering."
    "Suddenly noticing that I haven't even brought the cigarette back to my mouth the whole time, and it's almost down to the filter already, I pick it back up."
    "Like I'm making up for lost time."
    "Eris looks similarly invested in pretending to be somewhere else."
    "Then, she speaks."
    eris "I don't get you, Roman. I really just don't."
    eris "I'd kind of hoped I'll be able to figure out it out, and you know how much I hate to give up, but... I think that's it. I give up."
    roman "Really? You promise?"
    eris p2 e5 "Seriously? Is that what it's going to be like?"
    eris "Are you just being a dick on principle? What the fuck is it with you?"
    eris "I'm {i}trying{/i} to--"
    roman "To do what? I'm listening. I'm sorry if I'm being a dick, it's the hours getting to me. What are you trying to get out of me?"
    show eris p1 e1 at centered
    "Now, again she's quiet."
    roman "Really? That's all? After all I've said?"
    eris "After all we've done?"
    roman "Yeah."
    eris "No shit."
    "I inhale, deeply, so much that the smoke's burning the back of my lungs like it's high school all over again and I've no idea what I'm doing."
    "Something between a cough and a spit comes out."
    "We both ignore it."
    "Eris turns towards me."
    eris p3 e8 "You never gave me a straight answer, you know?"
    eris "One way or another, no matter what I do, you {i}always{/i} dodge the question."
    roman "Or maybe I'm answering it every time, but you don't want to hear what I'm saying."
    "Her brows furrow."
    eris p1 e1 "Why did you leave ARTech?"
    "I exhale."
    "Smoke snakes out of my mouth in psychedelic whirls and whorls."
    "Just like I thought. Cat's finally out of the bag. Cards on the table. Gloves on the floor."
    "Elephant in the living room: gone and poked, a big, juicy banana dangled in front of its face."
    roman "Because it bored me. I got tired of it."
    roman "Same as I told you before."
    eris p2 e5 "Quit with it, won't you? I don't buy that."
    roman "Why?"
    eris "Because--"
    eris "--because that doesn't make any sense!"
    eris "This is life, Roman. This isn't a game and you aren't a child."
    eris "You don't just go and quit {i}life{/i} because it bores you. That's just how it is."
    "I chuckle."
    roman "Really? Jesus, are you listening to yourself?"
    roman "I didn't quit {i}life{/i}, I quit ARTech. What exactly are you suggesting here? That I was born to do this? Like, Christ, {i}you{/i} sure as hell weren't born to do this. Why me?"
    eris p3 e8 "But--but you were so..."
    eris p1 e1 "You were so {i}good{/i} at it!"
    eris "You still are! You just showed that!"
    roman "Oh? So that whole 'renovation' thing really was just to try and get me to rethink this whole thing through? You know, I had my suspicions, but I guess I just wanted to think I could trust you far too much for that."
    roman "Sorry about that. Won't happen again."
    eris "Roman! Please! Can't you be serious about this for a moment?"
    roman "I am being serious. I don't know if you are."
    roman "Why should it matter if I was good at it? I hated the job. It made me miserable."
    roman "Sure, it paid nice, and the benefits were great, but I don't give a shit about that stuff. I give a shit about waking up in the morning and not feeling like going to work because I can't stand the thought of what it's going to be like."
    eris p2 e5 "'What it's going to be like'? What exactly did I do? Hold you down and waterboard you? It wasn't torture, it was your job. It was reality. {i}Life{/i}."
    roman "See? See?! You're doing that same thing again. That thing where you imply that my {i}job{/i} was, is, or should be my {i}life{/i}."
    roman "I don't know what it was like for you, but that's just not how I roll. And for your sake, I hope it isn't how you do, because if that's the case it's not even a wonder if you're feeling so empty inside you need to go to this ridiculous lengths every single fucking time in some pathetic {i}scheme{/i} to rope me back into yours."
    eris p2 e3 "Wow! Are {i}you{/i} listening to yourself? What is with this shit? 'How you roll'? What are you, fucking sixteen?"
    eris "You had an amazing thing going in ARTech! You could've had a future! You got a gift and you're squandering it! There's no other way to say it."
    roman "Well, guess what? I don't give a fuck. 'Gift'? I'm not a wizard, I'm not a superhero, I'm some asshole nobody who figured he'll go get a BE, see if there're any nice jobs that way."
    roman "Why the hell is it my {i}problem{/i}, of all things? I don't need you to come punish me for doing well at it."
    eris "No, you don't! You're punishing yourself well enough! If you'd stayed, you'd have been serious business by now, you know that? You could've been heading your department."
    eris "Instead the two of us are here, in this dump, in a literal fucking alley behind a pub, smoking and shouting at each other like a couple of drunkards."
    roman "I never asked you to follow me!"
    eris "You never thanked me for it, either!"
    roman "Why should I have?! I never {i}asked{/i} you! I didn't {i}want{/i} you to!"   
    show eris p2 e3 at transform_hide
    hide eris
    "She takes a step back, turning away for a moment, then looking, noticeably, towards the door, then back towards me in a ridiculous, spiraling dance of indecisiveness and doubt."
    "Just because I'm not prancing about, though, doesn't mean I feel any better about this."
    "I didn't want this to happen. This, exactly. I've been trying to avoid it all along."
    "But if this is what it's come to, this is just what it's going to have to be."
    "Eris recollects herself, pulling out one of her own e-cigs. I instinctively take out my lighter to give her, but it is, of course, pointless."
    show eris p3 e8 at centered
    "She draws on the device, slowly."
    eris "It really gets to me, how little you care about shit."
    eris "It's like you're doing this on purpose."
    eris p2 e5 "Just to show me up."
    eris "Like you'd make yourself miserable and sacrifice however much you need just so you could go and say that you did. So you could say I'm wrong."
    roman "You know it's not like that. You're the one who's sounding like a little kid now."
    roman "The world doesn't revolve around you. Not everything I or anyone else does is aimed to hurt you."
    eris "Everyone else, I'll let them speak for themselves."
    eris "You, I'm not so sure."
    "An exhalation. Pale vapors winding out."
    eris p2 e7 "You like {i}so{/i} much to act like you give a shit about the most pointless things nobody else does."
    eris "Whiskey and jazz and pool, am I right? You talk like it's your fucking religion."
    eris "But you don't {i}really{/i} give a shit about any of that, either, do you?"
    "She lets out a bitter, quiet laugh."
    eris "'Special Whiskey Pebbles.'"
    roman "Shut up. That was days ago. And just so you know, I went and checked and the atomic structure {i}does{/i} make a difference."
    show eris p1 e10 at centered
    "Her laugher grows."
    eris "Whatever. It doesn't really matter. Isn't that the point?"
    eris p1 e1 "You never even bothered to check that when you went and spent money on them. You didn't care about that."
    eris "You just wanted to have something special, that nobody else has. Something you could lord over them that you know about and they don't."
    eris "'Yeah, these are, uh, {i}special{/i} pebbles, you see. I wouldn't have thought a pleb like you would be familiar.'"
    eris p2 e4 "What a show."
    eris "I bet you could give me the names of eight jazz singers right now if I asked you, but if I went and actually did, you couldn't give me the names of three songs by each of half of them."
    eris "You know why that is, Roman?"
    eris p1 e1 "It's because you don't. Really. Give. A. Single. Shit."
    eris "You don't care about and you don't want to {i}be{/i} the guy who cares about jazz, you just want to be the guy people know cares about jazz. Or anything, really. That, that's important to you."
    eris "Now it's jazz. What was it last time, remind me? Lifehacks? Ditch the car and walk to work? Put on your shirt with both hands?"
    eris p2 e5 "And before that, was it Renaissance painting? You bought some expensive garbage then, too. Then you complained that it was only a replica, because it turns out they haven't actually made any new and affordable 16th century art since the 16th century. Who'd have thought?"
    eris "You go on and on and on about how evil and fake AR tech is, but you know what?"
    eris "You were just born with the fake shit built in. You don't need it to see things."
    "My cigarette's burned out long ago. I barely noticed it was still in clutched between my thumb and my finger, filter smoking."
    "I flick it away onto the grimy asphalt of the ally, letting the shadows of the building above us swallow it forever."
    "This is bullshit. I don't need any of that."
    "I'm not going to just stand here and let her talk to me like that."
    "Eris brought that on herself."
    roman "What's with that soap opera crap?"
    show eris p1 e2 at centered
    "Her head tilts dangerously. I don't care."
    show eris p2 e5 at centered
    roman "What? You thought you were the only one allowed to talk shit?"
    roman "Don't start that fire, Eris. You want to talk to me about caring for stuff? How about you look in your AR mirror, first?"
    roman "You make such a show of being the diligent worker, wherever you are. ARTech, Arcady. It doesn't matter to you, right? Earliest to come, latest to leave, always showing initiative, always giving all of yourself to the job, right?"
    roman "I call bullshit on that. You don't really care for anything, you just want it to look that way from outside. The only difference between us is you're more stuck up about it."
    eris "Excuse me--"
    roman "--I'm not finished."
    "I cut her sentence, sharply and painfully."
    roman "You make such a production out of how much you care, but what is any of it even {i}for{/i}? I thought you had a passion for what ARTech was doing, but then I leave the company and you just track me down to the goddamn {i}club{/i} I went to wait in, instead?"
    roman "Good thing you can sort-of-sing, huh? Imagine if you had to find another way in here. Probably would've had to convince Parker Arcady needs a finance department. And the funny thing is, you'd have done the job."
    roman "You hear that there's an 'improvement' you could make to the systems and all it'd take is so-and-so however many nights without us sleeping, and it just seems so natural to you that we both should commit ourselves to it."
    roman "But why? Why any of it? Because that's just what 'grown ups' do? Because that's the 'harsh reality' we live in? Because that's {i}life{/i}?"
    roman "You don't go to work because that's the point of existence, you go to work because you have to if you want to make {i}money{/i}, and you spend that money on what you care about."
    eris "You sound like the spoiled brat you are."
    show eris p3 e8 at centered
    roman "Maybe. But at least I'm sounding like what I am. I'm not trying to sound like anything different."
    roman "You don't have anything. Not really. You act like you do, but the truth is, at the end of the day, you've done all of this and you've gone so far and earned all this money, and then what?"
    roman "What do you even do with it, besides looking for whatever ridiculous way to improve your workplace some more? You aren't even home enough to be able to enjoy... any of it."
    roman "My problem isn't that I don't care about anything, it's that I care about all of it. You want to judge me for not being able to choose between jazz and painting? Well, fuck you! Why should I?"
    roman "There's so much out there that's so much more interesting than {i}this{/i}."
    roman "This boring, everyday {i}shit{/i}. That stupid, static, going-nowhere {i}grind{/i}."
    roman "There's got to be something else beyond it. I can't--"
    roman "--I can't stand the {i}thought{/i} that there isn't. I can't believe the world is that {i}boring{/i}. That it means so fucking little."
    roman "There's got to be {i}something{/i} out there. There has to be. {i}Anything{/i}."
    "Without even noticing, I'm the one who's now started shaking. I'm the one who must look pathetic from outside."
    "My heart beats fast and hard. My face is flushed."
    roman "I was suffering in ARTech, and you know what? I'd have suffered anywhere else just the same. I can't take that shit. It's boring. Everything is so boring."
    roman "I'm suffering here all the same."
    roman "And the way I see it, there's only one real connection."
    show eris p2 e5 at centered
    "She makes a sharp, violent, sucking sound, taking in a breath so fast it has to be painful."
    "I regret my words the moment they emerge from my mouth--"
    "But it's already too late for takebacks."
    "Eris' lips move, but all I can hear is mumbling."
    "Then--"
    eris p3 e8 "Fine."
    eris "Have it your way."
    eris "I don't want to see {i}you{/i} suffer."
    "Her hands, clenched into fists, shake furiously. She opens the back door so forcefully the metal crushes against the concrete of the wall."
    show eris p3 e8 at transform_hide
    hide eris
    play audio backdoor_openhard
    eris "Hope you enjoy your break."
    play audio backdoor_closehard
    "The door closes behind her with the same, deafening force of finality."
    "I'm left all alone with the smoke."
    return

label A1_07r_r:
    "She stops waving, minimizing the window in front of her out of habit with a brisk flick of her wrist, and turns a baleful stare towards me."
    eris p2 e5 "Fuck you. My shift's over."
    eris "If you've got nothing good to say, shut up or buzz off."
    "I literally stumble back at that. As in, I very nearly trip."
    "It's not just how forceful she is -- and she is -- it's how unexpected that reaction was."
    "Haven't seen her like that since overtime at ARTech."
    "Which, given the circumstances, does make a lot of sense."
    roman "Jesus, someone's cranky. What's the matter?"
    eris "The matter is I'm working on something and it's getting nowhere {i}and I'm busy{/i}. I don't expect you to sympathize."
    roman "Anything you need help with?"
    eris "It's none of your business."
    show eris p2 e5 at transform_hide
    hide eris
    roman "Ooookay. Alrighty, then."
    "I pick up the phone, wiggling it in the air for a moment as if from an irrational need to justify to her why I came, then place it back in my pocket."
    roman "You go ahead and have fun doing whatever it is, eh? Don't forget to turn the lights off when you're done."
    roman "Seeya."
    "I shrug and turn back for the door, but just as I lay my palm on the handle--"
    eris p3 e8 "Wait! Roman, hold on a second!"
    roman "Huh?"
    "Eris waves the screens away from her face and sinks back into her chair like a deflated balloon, rubbing the bridge of her nose."
    eris "Look, Roman, I'm sorry, alright? It's just the tiredness speaking. I've actually been here for a while."
    roman "No shit."
    eris "Well, yeah, but that's just how it is, isn't it? Jobs don't just do themselves."
    roman "I guess. Apology accepted. Bye--"
    eris "Wait! I wasn't finished."
    eris "I think I actually {i}could{/i} use your help here. Since you've volunteered."
    "I take my hand off the handle and turn to look at Eris, leaning back on the door for support."
    roman "I didn't volunteer, I was being polite--"
    roman "--but alright, shoot. What's this all about? You running some shady backroom business here I wasn't aware off?"
    eris p2 e7 "Trust me, I wouldn't have gone and told you if I was. This is strictly the kind of deal I know you could give me a hand with."
    roman "Go ahead."
    return

label A1_07r_c:
    "She stops waving, minimizing the window in front of her out of habit with a brisk flick of her wrist, and turns towards me with exhausted eyes."
    eris p3 e9 "Not now, Roman. My shift is already over so...."
    eris "I'd really appreciate it if you could give me the space to myself this evening."
    roman "Anything I can do to help?"
    eris p2 e5 "I can handle it, Roman."
    "I'm incredibly pissed off right now."
    "I guess it's not even her fault, that's just how she is, but the monotony of the work day begins to overwhelm me "
    "I haven't felt like this since my time over at ARTech."
    roman "What, so I'm not even allowed to talk to you now?"
    eris "...What are you talking about?"
    roman "Why the hell are you working late?"
    eris "It's really none of your business."
    roman "Really? This is just like ARTech all over again!"
    roman "When I thought we had already put this stupid bet behind us, are you still trying to one up me?"
    eris p2 e3 "Are you seriously-?"
    eris "Look, all I'm working and getting nowhere on is general improvements for Arcady."
    eris p2 e5 "This isn't for any nefarious purposes, so if you're going to stand there and be and be an asshole then you can kindly. Fuck. Off!"
    show eris p2 e5 at transform_hide
    hide eris
    roman "...Well, alright."
    "I pick up the phone, wiggling it in the air for a moment as if from an irrational need to justify to her why I came, then place it back in my pocket."
    roman "Go ahead and have fun doing whatever it is without me then. Turn the lights off when you're done."
    roman "Seeya."
    "I shrug and turn back for the door, but just as I lay my palm on the handle--"
    eris p3 e8 "Wait! Roman, hold on a second!"
    roman "What?"
    "Eris waves the screens away from her face and sinks back into her chair like a deflated balloon, rubbing the bridge of her nose."
    eris "Look, Roman, I'm sorry, alright? I'm really tired and I didn't mean to upset you. I've just been here for a while."
    roman "No shit."
    eris "I mean, that's just how it is, isn't it? Jobs can't just do themselves."
    roman "I guess. Apology accepted. Bye--"
    eris "Wait!"
    eris "I think...I actually {i}could{/i} use your help here. Since you volunteered."
    "I take my hand off the handle and turn to look at Eris, leaning back on the door for support."
    roman "So now that I'm walking away you want my help?"
    roman "You know what, fine. What's this all about? You running some shady backroom business here I wasn't aware off?"
    eris p1 e6 "I don't think I would have gone and told you if I was. This is strictly the kind of project I know you could give me a hand with."
    roman "Go ahead."
    return