label A1_09r:
    scene bg_club_2_during_work with Dissolve(0.5)
    "The hours kept running like wax."
    "Eris's big upgrade couldn't have taken that long, but there you had it. I'd taken my eyes off the clock and the next time I knew it, minutes all added up into months."
    "Concentrated, pure, distilled essence of wasted opportunities and nothing."
    "So dense I don't even dare to disturb the thought. I don't want to know how it'll look like if it went and exploded. What it'll do to the rest of my sense of reality."
    "I need a smoke. Gotta get this shit out of my mind."
    roman "Yo, Parker?"
    show parker p1 e3 at center_left
    "He spares me a quiet glance, bottle of synthequila still steadily held in one hand and glass still secure in the other. The customer wouldn't have even seen it."
    roman "I'll be out for a bit, that alright? Just going for a cig, then I'm back."
    show parker p1 e1
    "He nods. Amidst the shadows of the neon lights shifting across his face, my mind conjures a thin, but comforting smile."
    "I head for the back door."
    "It occurs to me that when I first arrived, I would inadvertently try to avoid getting in people's line of sight of the stage. I'd take the long way, behind the tables. Sometimes flattened against the wall."
    "But now I shouldn't have bothered. I certainly don't need to anymore"
    "The customers are barely aware I exist. Their blank gazes all rapturously fixed on the emitters we've scattered throughout."
    "They look so dumb sitting like this. Staring at the walls."
    "Submerging themselves in the virtual fucking wonderland I've gone and turned this place into."
    play audio backdoor_open
    scene bg_back_alley with Dissolve(0.5)
    play audio backdoor_close
    play audio ambient_city
    "I should be happy. Parker almost looked like he did my first day, and that's about as much as you can hope for from him."
    "We've just about multiplied profits in the span of a season. The customers keep pouring in. We got everything now: virtual band, virtual wallpaper, virtual music. None of that pesky 'reality'."
    "They buy drinks, they spend money, they tell their friends, rinse and repeat."
    "Parker gave Eris and I a raise and a bonus. I think hers was bigger--she was the one who 'showed initiative', after all. I didn't mind it. Mine was nice all the same."
    "Everything's right with the world. We've won."
    stop audio
    $ queue_music(music_nine)
    "My movements are fast and automatic. The cigarette's lit and held between my teeth before I'd so much as noticed taking it out of the packet."
    "I inhale, lean back, and try to float off and away to the zen of not giving a shit."
    "Watching, feeling a million miles away, the whorls of smoke rising lazily up in the air like transparent, abyssal fish. Flakes of ash drifting down in a sluggish and shadowy dance."
    "Closing one eye--"
    "Looking at them, down there, squinting at just the right angle--"
    "I can almost imagine seeing them falling into the beginning of a drawn, white-gray circle. Obviously, nothing but smoke is really there." 
    "My mind's just... desperate for it, I guess. Screaming at me to acknowledge a pattern in the air."
    "It's a cheesy, pretentious fuck, like that."
    "{i}You're an Arabian genie, Roman{i}."
    "{i}You're trapped in that magical circle.{/i}"
    "{i}All fiery and powerful--{/i}"
    "{i}All helpless.{/i}"
    roman "I need to escape this place."
    "It doesn't hit me that I've said those words out loud until I notice the tingling of the smoke in my throat."
    "When I first came here, I thought I'd finally found a place where I could belong."
    "Elegant. Classy. Old-school. Someplace where they cared about the same things I did."
    "The utter, complete opposite of ARTech."
    "I should've been happy here. It should have made me feel whole. I should've been able to enjoy this for years and years and years on end."
    "Then Eris had to come and drag ARTech all the way out here behind her."
    roman "Jesus. What's up with me today."
    "Experimentally, like it actually matters, I push one foot forward and break a half-formed circle of ash that has fallen to the floor. The flakes rise up into the air in a tiny, gray cloud, then evaporate off into nothing."
    "It doesn't do anything. I don't even know what got into me to imagine that it somehow would."
    play audio backdoor_open
    roman "Huh?"
    "I turn my head back towards the door, cheeks burning like I'd just got caught with my pants down."
    show eris p1 e2 at center_right
    eris "Roman?"
    "Eris' face pokes sheepishly out of the entrance. Her eyes are tired, but she doesn't look upset otherwise."
    roman "Yeah? Yeah, what do you want?"
    "She opens her mouth silently, in reluctance, glancing with uncertainty in both directions."
    eris "Is this a bad time? I mean, I could come back later if--"
    roman "What?--No, it's fine, it's--nothing. What did you want?"
    eris p2 e2 "Can I come over?"
    roman "Yeah. Sure. I'm not going to stop you."
    "She nods, the rest of her body following her head into the alley like some gangly cartoon character's."
    show eris p1 e1 at centered
    "Her first few steps are slow and cautious, like she's waiting for me to pull out a knife and lunge at her. Then she stops, takes a deep breath, regains her composure and stands up next to me, like normal."
    "She pulls out that disgusting e-cig of hers. Within moments, the whole alley fills with the sickening aroma of burnt cherry syrup."
    roman "So?"
    eris p1 e2 "...So?"
    roman "So, what was it you wanted to say? You look like you wanted to say something."
    roman "Can't think of any other reason you'd suddenly go all bashful on me."
    show eris p2 e7 at centered
    eris "Yeah, guess so. No real need for that whole highschool routine."
    roman "And?"
    "She takes another deep, long lungful of cherry vapors, then pulls the e-cig out her mouth and stares in the other direction."
    eris p1 e1 "So..."
    eris "Two things I thought I should say to you. To start, anyway."
    "What's with that show? Either she's won the lottery and trying to rub it in, she just found out she's dying, or she's playing some sort of game. I don't like two of those options."
    "Deciding to play it cool, I shrug and just motion for her to continue."
    eris p1 e2 "First: I wanted to say that I'm sorry."
    "Alright. That was unexpected."
    "I suppose that does deserve me looking at her in the eyes."
    roman "Okay."
    roman "What for?"
    eris p3 e8 "For the past few months, and all that. Mostly the big project I dragged you into, but, like, counting the whole other time, as well."
    eris "I know that you came here because you hated it in ARTech, and I should've known you wouldn't like this any better."
    eris "Plus... I {i}guess{/i} you could say that I was kind of a hardass about it. You did a good job and I mostly just sat there complaining."
    eris p2 e7 "I was selfish. I admit it."
    "A silence stretches between us, one that she tries to break."
    eris "That takes some guts, doesn't it? Doesn't happen every day that I can admit I was wrong."
    eris p1 e6 "So there, you have your one thing that you can hold over me."
    "She says that, then stops, obviously trying to get me to reply."
    show eris p1 e1 at centered
    "But I... don't really know what to say."
    "My mind's still working the sentence over."
    "If she'd been another person and this had been another situation, I'd just blurt out one of those automatic 'okay, I forgive you's."
    "But in this instance, in a weird sort of way, I feel simultaneously like Eris doesn't deserve that...{i}and{/i} deserves far more than that."
    "So I try to give it some actual thought."
    roman "..."
    roman "Alright. Thanks."
    roman "That sure is very mature of you."
    "The words ring hollow in the quiet alley air."
    show eris p3 e8 at centered
    eris "...Okay. Well--"
    eris  p1 e1 "The second thing I wanted to say is this: thank you."
    roman "'Thank you'?"
    eris "--For the same thing, basically. You were a ton of help and I wouldn't have been able to do any of this without you."
    eris "Don't know if you've noticed, or if you, well, care about any of this stuff, but you did some pretty impressive work, and it shows."
    eris "It was my idea, but you did like eighty percent of the job."
    "I chuckle. More to break this growing uneasiness than anything. Moisten up my throat that's suddenly feeling all perched."
    roman "Just eighty?"
    eris p2 e7 "Fine, eighty five? Something around that."
    eris "Which brings me to..."
    "She turns towards me, back straightened up, suddenly looking all formal and proper, and shoves a hand into her pocket."
    eris "This."
    "She pulls out something and hands it over to me. Curiously, I peek down to look at it, and--"
    roman "{i}What?{/i}"
    "I very nearly choke on my cig, sending me into what could charitably sound like a cross between a coughing fit and a snicker."
    "In Eris' hand, neat as I'd have expected from her, without even crumpled ends, is a roll of bills probably as wide around as my neck, held together in a rubber band stretched so thin you can see the discolored strands where it's desperately trying to snap apart."
    roman "You're trying to pay me...in cash?"
    eris p1 e6 "I thought you'd appreciate the sentiment at least."
    roman "What...?"
    roman "You...uh, want me to smuggle you south of the border, or something?"
    roman "'Cause if you got in shit with some scary individuals, I'm telling you right now, you're on your own."
    eris p2 e7 "Why, aren't you hilarious?"
    eris p1 e1 "Now, take it."
    "It's funny how irony works."
    "Now I'm the one who's moving like they're trying to get past a sleeping tiger. Slowly, carefully, lifting my hand towards her before snatching the cash and pulling it back towards me."
    "Part of me says I should fiddle with it for a tad--like, throw it and catch it, or sniff it, or feel it around for flaws just to make sure it's real--but honestly, I wouldn't know how to tell anyway. It'd just be superfluous."
    "Besides, Eris actually looks genuine. I think that scares me more than anything else."
    roman "..."
    roman "...okay."
    roman "Mind me asking what this is for?"
    eris p1 e6 "Our bet."
    "I stare at her, confusedly."
    roman "What, you mean like--"
    eris "Yup. From way back then."
    roman "Like, the one we had about--?"
    eris "That one."
    "My eyes dart from the money to Eris' face and back, mind still racing."
    roman "...I didn't win it."
    roman "I mean, if anyone {i}did{/i} win, it was you, no?"
    roman "Your system's the one that actually worked."
    eris p1 e1 "But only with your help. And not the way I planned it in first place."
    eris "I tried justifying this to myself in all kinds of ways, but the truth is, I just can't think of that as my victory. The point was to show who was better at this, right?"
    roman "...I feel like that depends a lot on what 'this' is."
    "She shrugs, looking the other way and sucking the occasional bubble out of her e-cig."
    show eris p1 e1 at transform_hide
    hide eris
    "For a while, both of us just stand there, in silence."
    "A minute passes..."
    "Then two..."
    "I decide it'd be smartest to put the money safe in my pocket, at least for the time being--but other than that, neither of us is moving."
    "It's almost like I'm expecting Eris to object. Change her mind at the last moment."
    "Nothing."
    "My cigarette has long since ran out so I light another one. Neither of us says anything."
    "The break's not going to last forever, though."
    "I decide to be the one to speak first."
    roman "This is way, {i}way{/i} more than I expected."
    show eris p1 e1 at centered
    eris "I know. You've helped a lot with the upgrades."
    "Her voice is flat, casual, and businesslike. The tone you'd use to tell someone that, yes, it is now 4:15. The bus will be showing up soon."
    "Definitely not the one I'd use if I'd just given someone the kind of money that...well normally goes in a briefcase. Typically on a table alongside a pistol and the head of gagged policeman."
    "My mind just runs over all of the things I could do with it."
    "Lots of whiskey, for once. Get back most of the stuff Parker had me return to the store."
    "A pool table. Real one, wood and all."
    "Getting a new car."
    "Or finally..."
    "..."
    "Running away from this place."
    roman "You know--"
    show eris p3 e8 at centered
    roman "It'd feel really shitty having to look you in the face every day after taking this much--"
    "I raise my eyes to look at her face."
    "Before I can finish the sentence, realization coalesces in my chest like tumor."
    "Heavy and sticky and painful and huge."
    eris "Don't worry about it. It won't be a problem."
    "Silence."
    "The two of us turn to look away from each other."
    roman "...Where do you plan to go?"
    "I can hear her clothes shifting in discomfort."
    eris p1 e1 "Dunno yet. Just started really looking at stuff."
    eris "I've been thinking about this for a while. Way since the last time we've... you know. Talked."
    "I nod, slowly, wondering if I should say something that wouldn't really mean anything in the end."
    eris p2 e4 "You were right the whole time, Roman."
    eris "This isn't the place for me. I'm not sure what is, but I'm now sure that this isn't it."
    eris "This is your place. It's always been. I just intruded on it because I--I dunno, it seemed like a good idea at the time. Honestly, I can't..."
    eris "I don't know what I was thinking."
    eris p3 e8 "Maybe I could really devote myself back at ARTech."
    eris  "But without the team I used to have..."
    eris p1 e1 "No. I think I plan on looking into a company where I can start out a bit more humble."
    eris "There's a lot I still need to improve on, and I can't expect others to do the work for me. I can't overwork myself with two jobs again either. "
    eris "I'm ready to forge a life for myself that I can finally take full control of."
    eris p2 e7 "With a few thousand tech companies on this side of town alone, there's bound to be one that'd be able to fit my criteria."
    "I squint at her, like that'd somehow make it so I could really see into her."
    "Like I was suspecting that smiling face of hers was a mask, and she was hiding deeper emotions underneath it."
    "I don't know whether or not that smile is real, but in the end I know that she's serious."
    roman "And all that, just because of what I said last time?"
    eris p1 e6 "You don't need to apologize about that. Water under the bridge."
    eris "Like, you {i}could{/i} if you want to, but I'm not going to keep a grudge if you don't."
    eris "You said some mean stuff, I'm not gonna lie, but most of it was true. There's no point to me working if I don't know why, and I'm not going to keep living that kind of unfulfilled life."
    eris p1 e2 "I still don't buy into the entire 'work should be fun' lecture you gave me, but the gist of it was pretty on the spot."
    eris  p1 e1 "It made me realize that all this time I've been mostly... I don't know how to say it without sounding like a moron. Kind of like... I was only driven forward by inertia, you know what I mean?"
    eris "I never could stop myself from pushing forward, so I just kept doing that. For years and years and years."
    eris "Never really knowing where I was pushing myself to."
    eris p1 e10 "I never thought about it until now, but you know what? Maybe I've been following you all this time because you just seemed to be so good at that."
    eris p1 e6 "Not always doing the right thing or the smart thing, but at least doing {i}your{/i} thing. That's pretty cool. A little stupid, but cool."
    eris "So now that I've gone and figured it out..."
    eris p1 e1 "Only logical thing to do now get off my ass and do something."
    roman "Like leaving Arcady."
    "She nods."
    roman "So all that money...?"
    eris p2 e7 "Some of us can be responsible adults, you know. I didn't just go off wasting what we've been making every month."
    roman "These are your {i}savings{/i}?"
    eris p1 e1 "Relax, it's not all of them. I'm not {i}that{/i} thankful."
    eris "Just a little something for showing me the way, plus what I owe you for the bet. Most of it's just my last paycheck--Parker gave me this huge ass bonus for what we've done, and I wouldn't have known what to do with it anyway."
    eris "You said so yourself. I don't have anything I like to do. I want to fix that."
    show eris p3 e9 at centered
    "Eris bites her lip in what looks, for a moment, like an expression of uncertain melancholy. Like her previous, cheerful smile was just the mask that she wanted me to see."
    "Then, in the span of an eye blink, the moment's gone."
    roman "Good luck with that."
    "My voice sounds distant and brittle."
    "She nods then turns off the e-cig, waving in front of her face to disperse the vapors."
    scene cg_ri_neutral with Dissolve(0.75)
    eris p1 e6 "I'm going to try my best. I'll stay here for a couple more days, but after that, you won't have to see me again."
    scene cg_ri_smile with Dissolve(0.5)
    eris "You could have it like you should've: you and Parker, and this place. And the upgrade we installed, but that was the two of us, right?"
    eris "Maybe without me getting in your way you'll be able to make more of it. I know you have it in you, when you do what you want. You could probably make this a really great club."
    "Stowing away her cig, she pushes herself off the wall and heads back towards the Arcady door.."
    play audio backdoor_open
    scene cg_ri_neutral with Dissolve(0.5)
    eris p2 e7 "Good luck, Roman."
    eris "You keep doing you."
    #show eris p2 e7 at transform_hide 
    hide eris
    play audio backdoor_close
    scene cg_ri_noeris with Dissolve(0.5)
    "The sound of the door closing reverberates throughout the alley."
    "Objectively, it's probably nothing. A creak then a bump in a city full of car horns and shouting,  noodle vendors and stereos blaring out of open windows."
    "There's a club half a meter of concrete behind me, where they're playing music right now."
    "And yet--"
    "--yet it feels like an earthquake. So much that my stomach turns and bile runs up my throat, even if my feet obviously aren't moving."
    "I can feel it my bones. I can feel it in my shaking organs. The way my teeth rattle."
    "The silence is maddeningly loud once it's now just me. And the stupid thing is..."
    "...I know that it shouldn't be like this."
    "Or rather... I think I know. Known, in any case."
    "I wanted this. I've won."
    "I got enough money to leave this all behind stuffed inside my jacket."
    "Eris' just went and flat out told me I was right, that she's going away from here--"
    "I'll have this place to myself now. Much as it ever could've been, in any case. The way I planned since the beginning."
    "This could be {i}my{/i} place now. Somewhere my word goes, where I can enjoy the world I've chosen in peace."
    "All on my own."
    "Flicking my cigarette into the wind, I lower my gaze to the ground."
    "The circle of ash is still there. Smeared across the asphalt the one part my feet had broken through it."
    roman "Some genie I am."
    "I whisper it out for no one."
    "Nobody to hear me making an edgy fool out of myself. Talking all cool and dark like I haven't since the twelfth grade. Like that somehow made my words poignant."
    "Like it'd made me feel less hollow, somehow. Less like I haven't achieved anything, even though I got it all. Something to make that sense of meaninglessness go away."
    "Shaking my head, I turn back and open the door."
    play audio backdoor_open
    show bg_black with Dissolve(1.5)
    return
