label A1_09c:
    # TODO: Add Long Time Skip here.
    scene bg_black with Dissolve(0.5)
    play audio car_engine
    "It's hard to believe how quickly a few weeks passes when you're not paying attention, but..."
    "For the first time in my life, I'm not worried about the time that's being 'wasted' working at Arcady."
    "Whether it's the atmosphere, the new surge of customers, or even my relationships with the staff, I never expected every day to be a privilege ..."
    "It's almost like I've finally found--"
    play audio navcomp
    navcomp "You are currently driving--ten--MPH over the speed limit. It is advised to slow your current speed before authorities are alerted."
    "Some things never change, though."
    roman "Aw, give me a break. Can't a guy be excited to drive to work for once?"
    play audio navcomp
    navcomp "Please be aware that in cases of--pregnancy. Injury. Tardiness--speeding may cause unnecessary and reckless endangerment."
    roman "Being excited is still on the table then?"
    play audio navcomp
    navcomp "Please be aware--"
    roman "Alright, alright! I'm slowing down you piece of... garbage."
    "Conveniently enough, I'm already pulling into Arcady's back--and before the machine can inform me of doing so, I've already started pulling into my usual spot." 
    play audio navcomp
    navcomp "Are you trying to--"
    play audio navcomp
    navcomp "Would you like--"
    play audio navcomp
    navcomp "You have arrived."
    show bg_back_alley with Dissolve(0.5)
    "It only took a solid month--but for the most part, it seems like I've finally beat my car's navigation computer."
    "I take in the familiar back wall of the Arcady Jazz Club, then smile." 
    roman "Yeah... I have."
    "Hard to believe that I'm still here." 
    show parker p1 e1 at centered
    "I shut off the engine and pop out of my car, only to  curiously meet Parker's gaze as he steps through Arcady's backdoor."
    show parker p1 e5 at centered
    "It takes him mere moments to recognize that it's me, and so he sends me a kind smile and steps closer."
    roman "Morning, Parker."
    parker "Morning, Roman. Still a little strange to hear you drive into work when I'm making the rounds in the kitchen."
    roman "I'm just doing what you asked me to."
    roman "I'm still only a thirty minute walk away from here otherwise."
    parker "Oh, the joys of being young..." 
    "The club owner lets out a sad chuckle, shaking his head back and forth."
    "His eyes flicker over to my car, shooting a nod over to the backseat."
    parker p1 e1 "So, I take it you picked up what I asked?"
    roman "Yeah... it wasn't too hard." 
    roman "I certainly received a few strange looks though."
    "I grab the crate of bottles from the back seat of my car and pass it over to Parker, who accepts it graciously."
    parker p1 e5 "Well, I'm very thankful for this."
    parker p1 e1 "Grab the backdoor for me?"
    "I shoot him a surprised look, glancing over to the rest of the cars in the lot."
    roman "You're taking it inside? Have a change of heart about keeping the bottles in stock?"
    show parker p1 e3 at centered
    "Parker shoots me an interesting look--though one I interpret to be utter dumbfoundment."
    parker "You really want a repeat of what happened before? I'm not wasting this whiskey on people who won't appreciate it."
    roman "Fair point. So..."
    show parker p1 e1 at centered
    "He shrugs as I grab the door for him; the two of us proceeding to make our way through the kitchen and to the bar."
    scene bg_club_2_before_work with Dissolve(0.25)
    "He sets the crate on the bar counter and motions for me to join him."
    show parker p1 e1 at centered
    parker "Some of the other staff tried your whiskey and took a liking to it. I like to treat my employees at times, so..."
    "He pulls one of the bottles from the container and passes it to me."
    parker "This one's yours."
    roman "..."
    roman "You're not poking fun at me here, are you?" 
    parker "Did your whiskey night sour your taste for the drink?"
    roman "Well no, but... I would've bought my own bottle, right?"
    "Not much of a gift, but it's the thought that counts."
    parker "I would consider the cash I transferred you a sufficient enough payment..."         
    roman "Payment...?"        
    "I reach for my phone and check my balance, only to realize..."
    roman "This is--"
    roman "You do realize you overpaid, right?"
    "He gives me a small smile and pats my shoulder."
    parker p1 e5 "Keep up the good work, Roman." 
    show parker p1 e5 at transform_hide
    hide parker
    "Before I can even think about thanking him, he's already walking toward the back room. The conversation is over--and like always, it's back to being just another normal day at Arcady." 
    eris "Hey, Roman!"
    "One filled with familiar sounds and people."
    show eris p1 e6 at centered
    "I watch Parker leave before I turn to face Eris, who approaches me with a grin spread across her face." 
    eris "Looks like we have the same shift again, huh?"
    roman "Yeah..."
    "She's now eyeing me with a hint of concern, then sports her usual shit-eating grin--one I know all too well."
    eris "You look really out of it; I thought you'd at least be the perkier one on a morning shift."
    "Her eyes flash over to the bottles on the bar counter, her grin fading into curiosity."
    eris "What's with the alcohol?"
    eris "Wait, is that...?"
    "I place my bottle next to the crate and pull out another, then pass it to Eris."
    roman "This is yours, actually." 
    eris p1 e2 "Roman, what's going on?"
    "I really don't know how to answer her."
    eris p1 e1 "..."
    eris "Well, everything's already been straightened up, and we have some time before the morning crowd comes in..."
    eris p1 e2 "Join me for a smoke break?"
    roman "This early?"
    eris p1 e6 "I can share if you run out prematurely."
    "She sets her bottle against mine and works her way through the same door I came from, motioning me to join her." 
    scene bg_back_alley with Dissolve(0.5)
    $ queue_music(music_nine)
    show eris p1 e1 at centered
    "As usual, we're outside, in the same back alley, next to the same club, feeling the same air." 
    "It's just a normal day--but of course, everything is different."
    "I take a long puff from a cigarette I really shouldn't be smoking and stare absentmindedly at my nearby car."
    "There's a long silence between me and Eris--though it doesn't feel awkward or hostile at this point."
    "Being in each other's company has just become a way of life at this point."
    "In the end, I'm the one that ends up breaking the silence."
    roman "So what's up, Eris? Why are you in the club on a Thursday morning, acting like everything is normal?"
    eris "Isn't it? We're doing the same thing we usually do."
    roman "I'm pretty sure we've never smoked {i}before{/i} work. I'm used to colder air out here." 
    eris "Well..."
    "She takes in a big breath, as if preparing for some big announcement." 
    eris p1 e6 "I quit ARTech."
    "I nearly choke on my cigarette and clutch the paper a little too tightly, then turn over to Eris--who's nonchalantly blowing smoke towards the sky."
    eris p3 e8 "So that's my news..."
    roman "What do you mean?"
    eris p2 e3 "What do you mean 'what do you mean?' I quit! Do you need me to spell it out for you?"
    roman "You know what I mean, Eris. ARTech was your life... In fact, it's what made me--"
    "Quit as well."
    "The words catch in my throat, but I'm sure she caught onto what I was referring to."
    "That passion and drive to succeed in the company was a double-edged sword.But to see her throw it all away so casually would mean..."
    roman "You found another AR job?"
    show eris p1 e1 at centered
    "She nods." 
    eris "I knew I couldn't revive the Greenway project without your help, and I wasn't about to start another one so soon."
    eris "The biggest reason, though, was that I knew I never could work two jobs."
    eris "I know I can't... but that's OK."
    "Something about this just doesn't feel right..."
    roman "Well then."
    roman "When are you leaving Arcady?"
    eris p1 e2 "Huh?"
    roman "The second AR job... When do you start working at it?"
    roman "I mean, I'm a little disappointed that you're leaving when I..."
    "The words catch in my throat as with this morning, and I'm not sure how I want to say it."
    "As I'm trying to search for the words, she gives me a surprised look."
    eris p1 e1 "Don't tell me you're about to confess your love to me."
    "Another cough escapes my mouth."
    roman "{i}No!{/i} that's not--! Uh..."
    "I try and compile my thoughts before things get complicated."
    eris "..."
    eris p1 e6 "Pfft."
    eris p1 e10 "Ahahaha!"
    "Her laugh echoes against the walls..."
    roman "Eris, that's not what I was trying to say."
    eris p1 e6 "I'm sorry, I couldn't help it."
    eris "But I figured something was up."
    eris p1 e1 "So...?"
    roman "Parker is gifting the whiskey that I bought for him to the staff, though it turns out... he overpaid me."
    eris "By how much?"
    roman "A lot. Enough to leave Arcady--and even the city."
    eris p1 e2 "I see."
    eris p1 e1 "Well... that should be great, right?"
    eris "It's all you ever talked about while working at ARTech. It's all Parker talked about, too..." 
    roman "Parker talked about me leaving Arcady?"
    eris p1 e2 "Uh..."
    eris "Well he mentioned certain staff members being temporary hires; I just assumed-- I knew you wouldn't be staying is all."
    eris "But this was all only temporary in the end, right?"
    roman "Yeah..."
    "I breathe in and exhale a big puff of cigarette smoke--but somehow, it just doesn't taste the same as it used to."
    roman "That's just it."
    roman "Things were {i}always{/i} supposed to be temporary."
    roman "Now I have what I want--and since you're leaving Arcady, there isn't really a reason for me to stick around."
    roman "All my life I've been against routine, so I guess it's weird that I..."
    roman "I don't want to leave."
    "It feels good to say out loud."
    roman "I mean... wow, a fucking {i}jazz club{/i} of all places."
    roman "I've always been trying to find something to just desperately latch onto, and--{i}this{/i} is it." 
    eris "..."
    roman "So... what? Is it bad that I'm never going back to ARTech so I can work here?"
    roman "Is it okay that I don't care about that at all?"
    roman "I have a good thing going here, so..."
    roman "I'll be sad to see you go."
    eris "..."
    eris "Well... you don't have to be {i}that{/i} sad."
    eris "Worst case scenario, Parker just sets us on different days, right?"
    roman "What are you talking about?"
    eris "Roman, I'm not working a Thursday morning because I quit ARTech. {i}This{/i} is the AR job that I found--or, well, had."
    eris "Parker offered me a higher paying full-time position a while back, and I finally decided to take him up on his offer."
    roman "You..."
    roman "You're staying, then?"
    eris p3 e3 "What, do think I'm that bad of singer?"
    eris p1 e1 "I actually heard from Parker that I now have a loyal following. I might not even have to work tables anymore."
    "She blows a puff of smoke into the air, and a look of soft nostalgia crosses her face."
    eris "AR improvements, though... who knows?"
    "The look leaves her quickly though, replaced by a usual grin as she knocks an elbow into my side."
    eris p1 e10 "So spill it, you really think my last performance was that bad, huh?"
    "I can't keep the smile from my face, I know quite well how obvious her teasing is. If she didn't know me at this point, maybe it would have actually looked like I was making fun of her."
    roman "Of course not."
    roman "I'm just glad I'll still be able to work alongside a good friend."
    show eris p1 e2
    "The last of my cigarette burns away."
    eris p1 e1 "..."
    eris "Well... careful what you say."
    eris p1 e10 "You might make Parker jealous after all." 
    "The two of us share a smile, and then a laugh. Soon enough, Parker unavoidably becomes the topic of our conversation."
    eris "So where does he get all that money, anyway?"
    roman "A secret lover, perhaps? I wouldn't put it past him..."
    eris "Or maybe he's loaded and is just running Arcady for fun?"
    roman "But then why would he care about wanting to bring more customers in?"
    show eris p1 e6
    "Eris's smile falters a little, her expression shifting more into slight curiosity."
    eris "Hm?"
    "It's not like I forgot the event that would start the foundation of our relationship."
    roman "Our employee of the month competition... Parker started that because he wanted more revenue for the club, right?"
    show eris p1 e1
    "She nods, now understanding where I'm coming from."
    roman "So why would he..."
    "Why would he set up a competition that didn't need to happen?"
    "After all, if he needed the money then all of his generosity wouldn't have really made sense up to this point."
    "And if he really wanted us to avoid fighting, then why would he purposefully put us together, rather than schedule our shifts far apart?"
    "Was it really due to Eris's conflicting schedule?"
    "Or maybe--just maybe--he tried to do the best thing that no one had ever tried for us."
    "He taught us how to listen."
    eris p1 e6 "We should really thank him."
    roman "Yeah..."
    "Or maybe we were just reading too far into things?"
    "Either way..."
    eris "Roman?" 
    eris "I know I've said this a lot, but thank you."
    eris "You know, for being a friend to me when I really didn't deserve it."
    roman "Well, we both needed one."
    "...Things really did work out in the end."
    "All that's left of my cigarette is a burning nub, one that I shove into the nearby smoking receptacle."
    eris p1 e1 "You finished smoking?"
    roman "..."
    roman "Yeah... I think so."
    eris "..."
    eris "Okay, me too."
    eris "Let's head inside; our break is bound to be over already."
    roman "Yeah, either than or have Parker send out a search party."
    eris p1 e10 "He could always fire us."
    roman "Now wouldn't that be something...."
    show eris p1 e10 at transform_hide
    hide eris
    "The two of us share a laugh as we casually make our way inside."
    "We're heading back to a home that we both have found."
    "Back to Arcady, the garden of an old and new world."
    show bg_black with Dissolve(1.5)
    return