label A1_07c:
    # TODO: Add Long Time Skip here.
    scene bg_club_2_before_work with Dissolve(0.5)
    "After that, the days seemed to just pass me by."
    "I guess it just showed how much energy I was putting into that stupid bet with Eris."
    "So now that that whole business is behind us...all I've got now is just the regular work at Arcady. God knows there hasn't been a sudden new customer boom because of our efforts."
    "It's same as it always was, except now something feels different. Time's getting all funky in very unfamiliar ways."
    "For the first time in my life I'm able to slow down and breathe. There isn't any crazy expectation to prove myself now, both myself and Eris failed what we were setting out to do."
    "And at the same time, unless I'm paying attention, it feels like life's passing me by in a nonchalant haze."
    "I come to work in the evening, spend what feels like seconds waiting tables, cleaning the floor, listening to Eris sing for really the first time, and then...bam: it's morning. All that time implodes into one instant 'nothing has changed', but..."
    "I get back home feeling better than I have been in a long time, strangely without having actually {i}accomplished{/i} anything different."
    "Either something's gone weird with some high-energy quantum whatchamacallit at the nearest university--"
    "--or I'm sinking into a routine again. Only comfortably this time."
    "As much as I'm all for the cohesion of the time-space continuum, I...really don't know how I feel about this new development."
    "Everything feels right, but old habits are desperately telling me to flee."
    "I'm all too afraid that something's bound to go wrong."
    play audio [backdoor_open, backdoor_close]
    $ queue_music(music_seven1)
    scene bg_back_alley with Dissolve(0.5)
    roman "There goes another night..."
    "My shift over, I say goodbye to Parker, pick my jacket off of the hanger and leave through the front door, but not before waving kindly to the guy with pink bangs who leaves big tips."
    "The air's warm and moist outside. In fact the sounds of the city, at this hour, feels quite distant from the cool hum of music coming from Arcady."
    "Thankfully it has never been too long a walk back to my apartment, but it can still be a trek on particularly hard working days."
    "Maybe it's the day to day routine getting to me, but I feel myself itching to just change something about today."
    "For the sake of a change of pace I decide to head for the nearest bus station."
    "Thankfully I catch a bus bench at the end of the street. I sit down, stretch, and glance aside at the timetable to see when the next bus is arriving."
    "Despite the sign just being all dust and scratches, it's a little refreshing to catch some tangibility to the world around me."
    "Still there are those annoying little white bars that tell me that the sign I'm seeing is probably a decade out of date."
    "If you don't want to wait long you're supposed to pull up your display to check an updated schedule. I guess it is getting late enough to check."
    "I reach for my pocket to take my phone out."
    roman "..."
    roman "...Huh?"
    roman "What the--"
    "Fiddling around in my pants pocket, then my jacket pocket, then my other pants pocket for a short minute produces little more than air, lint, and a ball of mush that could have been anything in a past life."
    roman "Well...shit."
    "I try tracing my steps back to the beginning of my shift. I must've left it inside when Eris started on this one song, and I pulled it out to check which one it was and--"
    "Well, at least it should still be at the staff only area, if I remember correctly. I mean, Parker's probably got better things to do than steal his employees' electronics and Eris wouldn't be caught dead with any device over six months old."
    "I laugh at the thought and turn back towards the club."
    play audio [backdoor_open, backdoor_close]
    scene bg_club_2_after_work with Dissolve(0.5)
    "Parker's nowhere to be seen, and it seems the rest of the crowd has already dispersed for the evening."
    "I make my way towards the staff area, quickly spotting my phone on the table. As I'm about to leave, though, my attention shifts towards a sight as unexpected as it is comfortably familiar."
    show eris p2 e3 at centered
    "Sitting at the table with a strained, focused, almost desperate expression is Eris. Her shoulders are slumped uncomfortably and from the wrinkles under her eyes you can imagine she's been here a while."
    "Her lips are trembling in frustration. Her foot taps absentmindedly on the ground in an uneven pace."
    "From the way her eyes are fixed on thin air and how she's waving her hands, this is one hell of an intense web surfing session she's doing."
    "I pull out my phone to check. Through the display, the myriad windows and screen floating in the air in front of her become clear."
    roman "Online shopping while at work? What's the matter, Parker forcing too much overtime on you?"
    if scene_5_rivalry:
        call A1_07c_cooperation from _call_A1_07c_cooperation
    else:
        call A1_07c_rivalry from _call_A1_07c_rivalry
    "She proceeds to show me her device's screen with a few menus opened."
    eris "Well, so far I'm looking at trying to upgrade Parker's old stuff. The right way this time."
    roman "How so?"
    eris "Well, I'm thinking about trying a firmware upgrade and a few new USB5 cables to make things smoother around here."
    roman "Seems fine to me. Did Parker approve the change this time?"
    eris p2 e4 "He did, actually."
    eris p1 e1 "Just so long as I don't go too overboard again."
    "I shoot over a sly grin."
    roman "Well, alright then."
    roman "USB5's are a dime a dozen nowadays, and the firmware upgrade should be free."
    eris "Well, I actually have a question about that..."
    "Eris shows me her screen again, pointing to a webpage about a certain software suite."
    eris p2 e5 "Parker's software is some open-source version of OmniSound, and all the plugins I can find {i}don't{/i} support the newer versions."
    roman "Okay, let me take a look. Swipe it over to my device."
    "Eris pushes a link over to my phone and I skim over the software she's looking at."
    roman "Ah, I see, FlareStudio 2. It's good software for what it's worth, but the interface is a pain in the ass."
    eris p1 e2 "You've used this before?"
    roman "I've... dabbled a bit on my own. I think I have a config file that might help out. I can bring it tomorrow if you--"
    eris p1 e10 "Oh, God, please. I've tried looking everywhere."
    roman "Sure. I'll be sure to grab it before my next shift."
    eris p1 e6 "That's great!"
    eris "Which also means..."
    eris p1 e10 "I can actually go home and rest."
    roman "Try not to work yourself too hard Eris. From what I've seen, you've been doing more than enough for Arcady."
    eris "I'll take note of that."
    eris p1 e6 "And hey, Roman?"
    roman "Yeah?"
    eris "I really appreciate what you're doing."
    eris "I'll see you tomorrow."
    show eris p1 e6 at transform_hide
    hide eris
    "She nods my way, and then proceeds to work her way to the Arcady staff room."
    "..."
    "It's a nice feeling to be left with a smile on your face."
    "Seeing Eris so uncharacteristically... {i}cooperative{/i} gives me just enough of an energy boost to be able to walk home a second time."
    "If this is the start of a new partnership between the two of us, then I really am looking forward to tomorrow."
    show bg_black with Dissolve(0.75)
    hide bg_black with Dissolve(0.75)
    "The next day I walk in to see that unsurprisingly Eris is already here, and hard at work on the console."
    show eris p1 e6 at centered
    eris "Hey!"
    roman "Eris, what did I say about working yourself too hard?"
    eris "Roman, I appreciate the concern but I'm fine."
    eris "I'm actually far too excited to work on this, especially now that I have your help to do it!"
    eris "By the way, did you bring the goods?"
    "I flash my phone, and an uncertain smile, over to her."
    roman "Got it. Here, I'll send it to you via NFC."
    "Eris's internal AR connects to my phone and grabs the file, and proceeds to immediately start working."
    eris p1 e6 "Okay...all that needs to be worked on now is the set up."
    roman "You have things covered for right now?"
    eris "Yeah, at least until I'm done."
    eris p2 e7 "Though I'll holler at you if something catches on fire."
    roman "Good to hear. Keep in mind that we actually do have work soon."
    eris "I'll try and be {i}extra{/i} careful then."
    show eris p2 e7 at transform_hide
    hide eris
    "In a flash she's already in her own world, but at this point I'm OK with that."
    "While Eris gets cracking on the AR platform, I decide to clean around the tables, wiping down each one out of habit before the start of the day."
    "On one of the tables though, I notice something I never expected to actually see."
    "Someone filled out a comment card that wasn't picked up."
    roman "That's rare..."
    "The few we've received have only come from loud mouthed tourists, who unsurprisingly always had something very strong and loud to complain about."
    "Still curious, I flip it over and start reading."
    "'I would have really liked to have seen more vegetarian options on here.'"
    "Expecting yet another harsh complaint, I'm actually met with something...that's a pretty valid suggestion."
    "We don't offer much in terms of healthy eating, aside from fries and two salads."
    "Wonder if Parker has more of these cards stashed away..."
    "I head back over to where Eris is working, her position still unchanged."
    roman "Any progress?"
    show eris p3 e9 at centered
    eris "Some... though I'm trying to figure something out..."
    eris "I just can't seem to..."
    "She glances my way, suddenly startled to find that I've been standing there."
    eris p1 e2 "Ah! Sorry, Roman. What's up?"
    roman "Just wondering, do you know about Arcady's feedback cards?"
    eris e1 p1 "No not really, why?"
    roman "Well, I found a card a customer wrote up that had a decent suggestion to it."
    "I hand her the feedback card and let her read it over."
    eris p1 e1 "More vegetarian options...? Now that you mention it, the menu does seem to be a few decades out of date."
    eris p2 e4 "I never thought that Arcady's menu could have been an issue, but I guess it would be a good idea to offer future customers some variety with their orders."
    eris p1 e1 "Not everyone wants to just come here to get drunk after all."
    roman "I was thinking I could take a crack at it while you worked on the AR system. I mean, business always starts pretty slow in the morning anyway."
    eris p2 e4 "It's a cool idea, Roman."
    eris p2 e7 "Just don't turn it into another whiskey tasting night."
    roman "Ah. Right. I'll keep things realistic for this one."
    eris p1 e1 "Well good luck with your end. I think I juuuust have things figured out on mine."
    show eris p1 e1 at transform_hide
    hide eris
    "And with that she's already back to throwing her into Arcady's AR console."
    "With nothing else to do, I steal a menu from the concierge desk and start taking a look."
    "The menu isn't bad {i}per se{/i}, but there's a few places that could use some more attention."
    "Burgers, for example. We could go for a black bean burger as an option. Tack on an extra 75 cents or something."
    "..."
    roman "Our two salads come with...bacon? How is that even a salad anymore?"
    "A quick search online gives me a few ideas for additional 'bacon-free' dishes. I write them all down so that Parker could have wider selection to choose from."
    "So far on my end, things are looking pretty--"
    eris "Shit! No!"
    "Out of the corner of my eye, I see Eris angrily slap the nearby countertop."
    show eris p2 e5 at center_right
    roman "You okay?"
    eris p1 e2 "Oh, was I loud?"
    roman "You could raise a few decibels if you wanted to shatter eardrums."
    show eris p3 e3 at center_right
    "She somehow manages to look even more stressed out than yesterday."
    eris p2 e5 "Well I'm sorry but--I put in your config file, which seemed to work out okay at first, but then system treats it like it's not actually working!"
    eris "This entire thing just doesn't want to work for me!"
    roman "Yelling at it might not contribute to a solution then."
    eris "I mean... yeah but..."
    eris "..."
    eris "Roman, I hate to always rely on you like this but... can you take a look?"
    roman "..."
    "It... kind of feels good to be relied on."
    eris p1 e1 "...What?"
    roman "Nothing, just in thought. Let me take crack at this."
    "Eris hands me the console and scoots up next to me."
    show eris p3 e3 at centered
    roman "A little personal space would be nice."
    eris p3 e8 "Ah, sorry!"
    eris p2 e4 "I'm just a little enthusiastic about this is all."
    "She shifts back a bit, giving me some breathing room."
    "I start by checking the settings on the console."
    "She's done a great job here with hooking up all the devices and getting the plugins loaded, but it looks like she forgot to update the firmware."
    roman "Eris, did you really forget to update this?"
    eris p3 e9 "Huh? I'm pretty sure I did, right?"
    roman "Well, I'm pretty sure the screen isn't lying. Take a look."
    "I show her the outdated version number on the console; the system has even helpfully noted that the software needs an update in rather big font."
    eris p2 e5 "Shit. It didn't update? Why didn't it update?"
    roman "Did you remember to run the program after rebooting? It prompts you."
    eris p2 e3 "I know that! It... I guess it just decided not to update on me."
    roman "As a practical joke maybe?"
    eris p2 e5 "Ugh, Roman, just... give me a second with that--"
    $ queue_music(music_seven2c)
    "She reaches for the console, trying to tug it away from my hands."
    roman "Whoa, hey. Eris!"
    eris "Just lemme do it! I'll get it done faster, anyway!"
    roman "Excuse me? What are you, five?"
    show eris p1 e2 at centered
    "Eris stops."
    roman "Didn't you just ask me to help you out? What's all this 'I'll get it done faster' bullshit?"
    eris p3 e8 "Well, that's... "
    roman "If you're gonna ask someone to help, let them help you before you try to wrestle the controls back!"
    eris p1 e1 "..."
    eris "Alright. I'm just...not used to this OK?"
    roman "Eris, it's stuff like this that made me--"
    "Hate working with you in the first place."
    "The thought passes my mind, and it used to be my only thought on the matter."
    "Yet I'd like to think things have the chance to be different."
    roman "Look, you keep wanting to do everything at once, but ultimately never can accept help with anything."
    roman "Frankly, it pisses me off to no end. No kind of work can ever get done when you're always trying to do the work of three people."
    roman "But you have people around you who can support you, coworkers you can {i}actually{/i} rely on so you don't have to work these crazy hours."
    roman "If you had just trusted us with some of the workload back then, things might have..."
    eris p3 e8 "Roman..."
    "For the first time that I can ever recall, Eris is at a loss for words."
    roman "Sorry for the rant."
    eris "..."
    eris p1 e1 "No."
    eris "I should be the one apologizing here. I got irritated at you for something I shouldn't have."
    eris p3 e9 "Just like all those other times back then."
    eris "..."
    eris "I guess I'm the bad guy here."
    roman "You're not a bad person, but your personality doesn't lend itself well to working in a team."
    eris "...Roman, have you ever had someone walk out on you before?"
    roman "...?"
    eris "It's a terrible feeling, to feel like you're not good enough for somebody."
    eris "You're with that person for long and then they just... leave."
    "So it's about ARTech in the end?"
    roman "Eris, I'm sorry for--"
    eris p1 e1 "You know someone your entire life. At least you think you do. You grew up loving them, and when you finally sure that you can rely on them they just--"
    eris p2 e5 "--It's like you don't matter anymore! Your entire family doesn't matter!"
    eris "And it's not just them. It's not just you. Everything it left out of your control, and if you sit around nothing is going to change about that!"
    eris "But you're never good enough! No matter how hard you work!"
    eris "No matter what job or hobby you have!"
    eris "No matter how much money you've earned!"
    eris "No matter-!"
    roman "{i}Eris?{/i}"
    "My hand reaches her shoulder and I realize she's shaking when I touch her."
    "It takes a few moments of breathing, but she calms down enough for me to remove my hand."
    eris p3 e9 "Sorry, I just..."
    eris "...I don't know what came over me."
    "She takes another deep breath as if to collect her thoughts."
    eris "Yeah, I can be stubbornly independent sometimes. I guess I can really work on that."
    eris "But..."
    eris e1 p1 "Roman?"
    roman "Yeah?"
    "She hands me the console again."
    eris "I really want you to know, that I trust you."
    eris "So here, take it and do your thing."
    roman "..."
    eris "Roman?"
    "In all the years I've worked with her, I've never heard her say that."
    "She's admitting that something is out of her control, and in the biggest twist of irony...I'm the one she's handing it to."
    roman "I... never had your trust in the past. In fact you were the last person I ever thought I could rely on."
    roman "It's kind of a weird feeling now."
    eris p2 e3 "Do you still want to help me?"
    roman "..."
    roman "Yeah, yeah I do."
    show eris p1 e1 at centered
    "I start again by checking the file location of the config file I wrote, as well as the plugins Eris downloaded."
    "Thankfully, they're all in the correct place. Once again, however, the software for the device is outdated, so it's stopping all plugins from working until an update happens."
    "I tap the 'update' button and start the installation process."
    "A couple of energetic beeps later, and the update completes."
    eris p1 e2 "Oh!"
    roman "Should be all set."
    eris p1 e10 "That's... awesome!"
    eris p1 e6 "I... you..."
    eris "Thank you so much, Roman!"
    "It's a sincere, relieved thank you."
    "If you had asked me if she was capable of this a year ago, I'd have laughed my ass off."
    "But seeing her now, after everything that has happened... it's really hard to feel angry now."
    roman "You're welcome."
    roman "Still, run a few tests just to make sure everything works the way you think it should."
    roman "That you can do on your own."
    eris "Sure, I can do that."
    roman "Okay, I guess it's time to start my shift now."
    roman "You can...holler if you need me. Just be sure to take some time and rest when you can."
    eris p1 e10 "You can count on it."
    show eris p1 e10 centered
    $ queue_music(music_seven3, False)
    hide eris with Dissolve(0.25)
    "And just like that, she's back to work again."
    "Yet overall I'd say that went..."
    "Well."
    "Way better than I ever thought could have been possible."
    show bg_black with Dissolve(0.75)
    hide bg_black with Dissolve(0.75)
    "The end of my shift rolls in, the late hours clearing out the crowds."
    "I try and check in on Eris, but Parker heads me off before I can."
    show parker p1 e1 at centered
    parker "Heading out, Roman?"
    roman "Uh, sort of. Need something?"
    parker p1 e5 "I just wanted to thank you for helping out Eris earlier today."
    parker "You two looked like actual coworkers!"
    roman "Heh, thanks."
    parker p1 e1 "I'm serious. You two have come a long way from being at each other's throats all the time."
    parker p1 e5 "Honestly, I'm quite relieved. I would have hated to fire the lot of you."
    roman "Uh... was it really that bad?"
    parker "Probably not. But in my experience, those kinds of feuds would tend to escalate rather quickly."
    parker "Kudos to both of you for keeping a cool head."
    roman "Thanks."
    roman "Oh--before I forget, I wanted you to take a look over something."
    parker e1 "Hmm?"
    "I hand over my notes and let him take a quick read."
    parker p1 e4 "Hmmm..."
    parker "So this is one of the things you talked about with Eris?"
    roman "Yeah, she encouraged me to go through it it."
    roman "If the club's budget and chef's attitude wouldn't be a problem, I think this is actually something viable we could look into."
    parker "..."
    parker p1 e1 "Budget won't be the issue."
    parker "But..."
    roman "But...?"
    "He points to a few of the options that I have written down."
    parker "These would be pretty easy to implement. Give me some time to work things out with the chefs, and I think these changes can be made."
    parker "If all goes well we can have a new menu by next week. I think the customers will like these."
    roman "Well, great! I'm happy I was able to help."
    parker p1 e5 "I appreciate that you found the time to bother with this today. I also appreciate Eris encouraging you to look into this."
    roman "Yeah...I'm glad she did too."
    stop dynamic_1 fadeout 5.0
    stop dynamic_2 fadeout 5.0
    show parker p1 e5 at transform_hide
    hide parker
    "He pats me on the back and wishes me a safe walk home. I did a good job today."
    "{i}We both did.{/i}"
    "I try and look out for Eris, but I can't seem to find her."
    "Maybe she really did take my advice to heart."
    show bg_black with Dissolve(1.5)
    return

label A1_07c_rivalry:
    "She stops waving, minimizing the window in front of her out of habit with a brisk flick of her wrist, and turns a baleful stare towards me."
    eris p2 e5 "Fuck you. My shift's over."
    eris p1 e2 "If you've got nothing good to say, shut up or buzz off."
    "I literally stumble back at that. As in, I very nearly trip."
    "It's not just how forceful she is--and she is--it's how unexpected that reaction was."
    "Haven't seen her like that since overtime at ARTech."
    "Which, given the circumstances, does make a lot of sense."
    roman "That's not like you... Something's up."
    "Eris opens her mouth to presumably weakly lash out again, but she holds her tongue."
    eris p1 e1 "I'm just tired and frustrated right now, Roman. I don't have time for this right now."
    roman "Maybe I could help?"
    eris "Please, just leave me alone."
    "I think back towards the last conversation we shared with each other...and frankly, I was a bit of an ass."
    "Yet despite never really being on the right foot, I can now see where Eris is coming from with these outbursts."
    "Hell, from the whiskey tasting event I'm surprised I didn't snap more the last time Eris brought it up to me."
    roman "Okay."
    roman "But I just wanted to apologize for the last time I snapped at you."
    roman "I was under a lot of stress too from that failed evening and...it was unfair of me to lash out at you like that."
    roman "So, I hope you finish up what you need to. Just remember to turn off the lights when you're done."
    "I turn to go, not really sure what I was expecting but glad I finally apologized nonetheless. It's a start moving forward."
    eris "Wait, Roman."
    "I stop and turn back to her."
    eris p1 e6 "Apology accepted, and I... actually {i}really{/i} could use your help. If you'd still be up for it."
    roman "Yeah, I would be."
    eris "That's...great to hear."
    eris "And thank you."
    return

label A1_07c_cooperation:
    "She stops waving, minimizing the window in front of her out of habit with a brisk flick of her wrist, and turns toward me with a tired smile."
    show eris p1 e1
    eris "Wrong on both accounts."
    eris "Sorry, just trying to focus here. I can't really talk now."
    "I literally stumble back at that. As in, I very nearly trip."
    "It's not just how forceful she is--and she is--it's how unexpected that reaction was."
    "Haven't seen her like that since overtime at ARTech."
    "Which, given the circumstances, does make a lot of sense."
    roman "Is something up? It's a little weird to see you working this late."
    "Eris opens her mouth to presumably to weakly chastise me, but she holds her tongue."
    eris p1 e1 "I'm just tired and frustrated that this isn't working. I {i}really{/i} don't want to talk right now."
    eris "I'm sorry, Roman."
    roman "You certainly seem like you have your hands full, but..."
    roman "Maybe I could help?"
    eris p2 e3 "...Huh?"
    "She looks me over with a confused expression, though the reality is that I'm a little surprised myself."
    "I think back towards the time we shared at ARTech together, how I did anything possible to avoid working with Eris."
    "We never really were ever able to get on the right foot, and maybe the full reason was because I never cared to."
    "Hell, from the whiskey tasting event I'm surprised I didn't snap more the last time Eris brought it up to me."
    roman "I'd like to help you, if you'll have me."
    roman "I mean, I've been told I'm pretty good working with AR tech after all."
    eris p3 e8 "That's... I mean..."
    eris "If it's not too much trouble for you. There's a few things I could use help in reviewing."
    "She still gives me a tired smile, but there's a little more life in her eyes now. "
    eris p1 e1 "I would really appreciate that, Roman."
    roman "It's no problem."
    roman "We're coworkers after all."
    "She nods."
    eris p1 e6 "Of course."
    return