label A1_03:
    show bg_black
    "Pulling the car back into the alleyway behind Arcadia's feels like sinking through molasses into another world."
    "One moment, you can't hear yourself thinking over the honks and the blares and the shouting and all that hustle and bustle of the street outside."
    "Then you drive back for ten more seconds, and before you can really mind it all that noise just fades out into... a world you have for yourself."
    "Just the soft hum of the engine, the gray, hoary whisper of the AC blowing at your face, and--"
    play audio navcomp
    navcomp "Are you trying to park in reverse?"
    "The navcomp's saccharine, hotel-receptionist voice pulls me out of my moment."
    roman "Nah. Just felt like trying something new. I'm actually in the middle of a traffic jam. Gonna ram into the back of that asshole in the gas-guzzler right about... now~"
    "The navcomp goes silent for a blissful second. Checking with the satellite, I bet. Gotta be cautious when the human's driving."
    "Hope it's not calling my insurance provider."
    play audio navcomp
    navcomp "Are you certain that you're in the middle of a traffic jam? Your position seems to be--"
    roman "Yeah, yeah. Can it. I can handle it fine."
    play audio navcomp
    navcomp "Are you trying to park in reverse?"
    roman "Would've been done with it a minute ago if you'd just let me focus."
    play audio navcomp
    navcomp "Would you like to activate auto-parking?"
    roman "Nope."
    play audio navcomp
    navcomp "Would you like to open a rear view screen?"
    roman "Nyet. They got those nifty little tchotchkes called 'mirrors' on cars now, thought I'd try see for myself how those work."
    play audio navcomp
    navcomp "Would you like to--"
    roman "Navcomp, off."
    "The cheery, fake voice cuts off in the middle of yet another helpful suggestion."
    "Good riddance."
    play audio car_off
    scene bg_back_alley with Dissolve(1.5)
    "Stretching my neck out the window, it {i}does{/i} kind of look like I might have a couple more meters to go, but I'm not pushing my luck."
    "Didn't just squeeze through that godawful afternoon traffic like some oiled-up fragging butterfly just to end up backing into a dumpster at the last second."
    "Guess I have it coming for insisting on driving a solocar, but between that and spending half an hour jammed in the tube with fifty slack-jawed ARses staring into space and waving their fingers around like a pod of virtual zombies, I'll take the car every day, thank you very much."
    "Now, to get out and move that precious, precious cargo where it needs be."
    play audio car_open
    "I walk around to the back, stretch my arms over my head until I can hear that satisfying *knack* my spine makes after a drive, then open the trunk."
    "Part of me thought it'd be easier to just put it in the back seat before I left home, but I just couldn't get that image out of my head of me stopping suddenly and the whole thing coming hurtling forward like a glass rocket and shattering to a bajillion pieces of wasted money."
    "Not to mention contests lost, egos bruised and Eris' smug face... smug-ing."
    "She doesn't know what's coming to her. I got this in the bag."
    play audio car_close
    "Spreading my legs to brace myself, like I used to do when transporting computer brains back in the day, I get my fingers underneath the crate until I can feel the hard wood right between the backs of my knuckles, and heft."
    "Heave--"
    # TODO: play audio bottles_rattling
    "Ho--{i}whoa!{/i}"
    "The contents rattle dangerously at the sudden movements. Looks like I'm going to have to do this slow and steady."
    "Which is a problem, since the thing's pretty damn heavy."
    "Gauging the distance at a glance tells me my knees aren't going to be pleased with me by when I'm done."
    "On the other hand, what am I supposed to do? Ask Parker for help? I'm only doing this because my honor's on the line, dammit."
    "Step by painful step, I make my way towards the door."
    # TODO: play audio bottles_rattling
    "That's it."
    "That's the way to do it."
    # TODO: play audio bottles_rattling
    "There, I'm almost there."
    "Just another meter, then to stretch my arm juuuust the right way to grab the handle--"
    play audio backdoor_open
    "I can feel the cool touch of the metal on my fingertips when the creak of the old door beginning to open hits my eardrums like the cocking of a gun."
    # TODO: play audio bottles_rattling
    scene bg_back_alley with hpunch
    roman "Oh crap oh crap oh crap--"
    roman "--phew!"
    "Exercising what little grace can be humanely mustered while carrying a load in two hands, I deftly manage to very nearly avoid killing myself in a very stupid way as I tumble backwards."
    show parker p1 e1 at centered
    parker "What with all the noise out--"
    parker "Roman?"
    "Parker's eyes move confusedly first to the box, then my face peeking out from behind it, then, with a stretch of the neck, to my car, then right back to the box, then to me."
    "His eyebrow rises by a fiendish, all-too familiar, fraction of a centimeter."
    parker "Fancy seeing you here, of all places. Don't you usually go about how good it feels to walk to work?"
    "Under different circumstances, I'd like to think that I'd have been able to pull out a comeback."
    roman "Uhm--"
    roman "I, uh, had those boxes to carry."
    roman "They're heavy."
    roman "Well, heavy-ish, in any case. Would've been a bit of a hassle."
    "Unfortunately, it just wasn't meant to be."
    "Parker nods slowly, leaning on one hip with the ease of someone who isn't just blocking the way of a person carrying a heavy object."
    parker "You know, if you didn't feel like you were being paid enough, the responsible thing would've been to tell me about it {i}before{/i} resorting to..."
    parker "What is this, organ trafficking? Drug smuggling? Bootleg ARoge games? They're pretty harsh on those last ones, nowadays."
    roman "Harr harr. It's my supplies for this evening's thing. The competition."
    parker "Competition?"
    roman "That bet I made with Eris."
    parker "Oh. That 'competition.''"
    roman "What--come on, don't be like this! You thought I wasn't serious or something? I'm a man of my word, Parker."
    parker "A modern day samurai."
    roman "Okay, look--I didn't want it to come to this, alright?"
    roman "But sometimes a man's gotta do what a man's gotta do, you know? I'm not going to spend the rest of my days here listening to Eris--I don't know, just {i}dissing{/i} me and, like, my whole way of life!"
    show parker p1 e5 at centered
    "Parker looks like he's trying very hard not to laugh. To his credit, he's doing a pretty good job."
    roman "Fine, so maybe not that far. But still, Eris started it. And if it's a fight she wants, then dammit, a fight's what I'm going to give."
    parker "Right. With that box?"
    roman "Pretty much."
    parker "Okay."
    parker "So now that you've got me thoroughly worried, may I be so bold as to ask what's in it?"
    "Now he's talking."
    "I don't even try to stop the smile climbing up the back of my mouth and onto my lips."
    "What can I say? I'm proud of this one."
    roman "You're gonna love this. It's your specialty, after all."
    parker "Oh? A whole crate of pretending to be hitting on tired office ladies?"
    roman "The other one."
    roman "Although I guess this can help."
    show parker p1 e5 at centered
    "This gets a wry laugh out of him."
    roman "What I got you here--"
    "I carefully take one hand out from underneath the crate to present it with all due gusto."
    roman "--is two, whole boxes of no-shit, bona fide, real-deal, genuine {i}whiskey{/i}, my good man."
    show parker p1 e3 at centered
    "Damn, I got him to widen his eyes a little. I'm on a roll now."
    roman "And not that Mexican Cornahol shit, either. None of that stuff. I'm talking serious booze here. 100\%, smoky, golden, just-short-of-a-decade-old bourbon goodness."
    parker "Pricey stuff."
    roman "You bet it is! Got them in this neat little boutique-kind-of-place I know a couple blocks off of my home. Made a special order and all."
    roman "Thing is, though, this is going to pay itself back in no time, right? I mean, how can you resist this? Anyone goes to a place like Arcady, they're gonna want a piece of these babies."
    parker p1 e1 "I see."
    "His eyes dart from the whiskey towards the car parked behind me."
    parker "What's it you got tied to the roof?"
    roman "Oh, that? That's the other part of my plan. Get this:"
    roman "Pool table."
    parker p1 e3 "Pool table?!"
    "He tilts his head aside to get a better look past me, now looking legitimately intrigued."
    parker "Kind of small for a pool table, isn't it?"
    roman "Well... yeah, I couldn't {i}actually{/i} get, like, you know. A real one."
    roman "Turns out you need people to move them and all that."
    roman "I just bought one of those 3D-printed prefab deals you put together on the spot."
    roman "I know it's not {i}the{/i} most authentic way of doing things, but I mean, it's miles and miles ahead of that simulated bullshit, right?"
    show parker p1 e1 at centered
    "He lets out a quiet hum of acknowledgement, eyes closed in thought."
    parker "So what's the whole plan, then? You got this whiskey and the pool table, and what now?"
    "I beam at him, pulling one of the leaflets I've printed out of my pocket and handing it over."
    roman "What do you think? Pretty brilliant, huh?"
    "Parker's eyes race to and fro across the laminated page, first taking-in the contents then stopping for a while to focus on the art bits. Just like I intended."
    parker "'An Old-School Whiskey Tasting Evening'?"
    roman "Exactly. Spent half the morning posting those everywhere I could think of. I'd have gone and done some online advertising, but that'd be using leather seats for a vegans' convention, right?"
    roman "If we're doing this right, we're doing this right. Old fashioned. Classy. Pure."
    "Parker bites on the corner of his lips, obviously mulling over how to respond."
    "Eventually, he settles for a shrug and a smile."
    show parker p1 e1 at transform_hide
    hide parker
    parker "Okay."
    parker "I'm willing to give it a shot. Let's see how it goes. You need any help getting those inside?"
    roman "It's alright, I got this."
    "Parker nods and turns back into the club. My knees cry meekly in protest as I lift back up the box at my feet, but after that 'a man's got to do' talk, I don't think I have much choice but to bear with it."
    "Now, back to business."
    scene bg_club_2_before_work with Dissolve(0.5)
    "Carrying them in aside, setting up the props for tonight's event took barely any time at all. That's one of the beautiful things about my plan: it's simple and efficient."
    "I can't even imagine what kind of convoluted electronic gimmick Eris would want to install here. "
    "The whiskey bottles are standing up like proud soldiers across the counter and inside the cabinets, glass gleaming, labels sparkling, ember contents shining in the warm Arcady lights."
    "My very own army of proper, old-school club-going experience warriors. Ready to leap up into Parker's hand and make the ultimate sacrifice to provide the customers with an unforgettable evening."
    "I've made some space for the pool table near the back and put it together all nice and easy. It's not the hardwood and green baize I've been hoping for, but at least it's {i}something{/i}."
    "It's {i}real{/i}."
    "All of this is so {i}real{/i}."
    "Waiting for the customers to start pouring in and filling the place up is agony."
    "I do get a jolt of excitement out of it each time one sits down and picks up the leaflet I've placed on the tables, though."
    "Seeing their eyes light up with curiosity. The way some of them pull out their credcards to check the balance or make those funny ARse air-motions to message their friends over."
    "Probably taking pics and posting them all over the net."
    "I keep one eye on my work and one eye on the slowly gathering crowd as the club begins to slowly come to life."
    "Much as I want to start this already, I know I'll only get one shot at a real fancy opening, and I don't want to waste on a partial audience."
    "In the meantime, I make use of whatever lulls in the action I can risk setting up the stage and connecting the mic. Kinda disappointing that this is kind of tech is mostly just plug-and-play."
    "Slowly but surely more and more seats are taken. The static noise of conversations and laugher grows louder and less distinct. Parker's now spending more time handing out drinks than chatting with drinkers."
    "This is it. Just a little while longer now."
    "I had over to Parker's for a few final preparations. He's just finished pouring one of the early-comers what has to be their third mug already, so he should have a free moment."
    show parker p1 e1 at centered
    roman "Yo, Parker. Doing fine?"
    "Parker takes his eyes off the indeterminate point in the distance his display must be floating in and faces towards me."
    parker "Much as can be. What is it?"
    roman "Think I'm about to get this show on the road. You got the bottles ready to go?"
    parker p1 e5 "Roman, they're bottles. They're in the cabinet. What else do you want me to do? Initiate a launch sequence?"
    roman "...Right. Well, just stay on top of things, okay?"
    parker "You know that's my job to tell you, right?"
    roman "Well, yeah, just making sure."
    parker "Consider yourself assured, then."
    roman "Thanks. I guarantee you, this is going to be amazing."
    roman "Oh, and I've been thinking--"
    "I point towards the stage behind me."
    roman "Is there any chance I can try and hook up a real mic up there, or are we stuck with that AR contraption?"
    show parker p1 e4 at centered
    "Parker eyes me with an odd look."
    parker "Why? The customers are all wired in, they hear it just fine."
    roman "Sure, but, I mean, it doesn't have all those little things, you know? No echoes, no tiny pieces of feedback, no--"
    parker p1 e1 "Roman, generations of sound technicians have toiled for more than a century to produce a system that runs as smoothly as this one does."
    parker "It isn't theirs, mine, and certainly any of my customers' fault that you found the bugs on older models charming. Is that clear?"
    roman "...Yes, boss."
    parker p1 e5 "Good. Now get up there and do your thing. I'm sure that if you do well enough, people would be willing to forgive you over the equipment not being faulty."
    show parker p1 e5 at transform_hide
    hide parker
    "Off the corner of my eye, I can see the guy with the mug already getting uppity again."
    "Parker notices him too, and, with a silent nod of approval, sends me away towards the stage."
    "My frustration with the sound situation evaporates to make way for anxiety as I make my way up the stairs."
    "With the lights behind me, it's hard to make out the customer's faces when I look aside, but I can tell roughly how many of them there are."
    "{i}A lot{/i}."
    "Heart beating like a doumbek, face burning, throat shaking, I pick up the mic in front of me and tap the end to grab their attention."
    "There's a moment of silence as shadowed faces turn to me. I take a deep breath, and open."
    roman "Good evening, ladies and gentlemen."
    roman "First of all, I'd like welcome all of you to Arcady and thank you very much for being here with us tonight."
    roman "We got a special treat planned for you this time, so you're all very much in luck."
    roman "Now, as you can see on the leaflets set on your tables, this is Arcadia's first-ever, but hopefully not last, old-school, authentic, whiskey tasting and pool night!"
    roman "That's right, folks: real whiskey, real pool. No virtual tricks, no electronic chicanery, no computerized prestidigitation. These ain't AR and these aren't illusions: this is all the real deal."
    roman "And I know what some of you might be thinking to yourselves: why do I need this? I've been enjoying the synthetic stuff fine enough so far. I've played virtual pool plenty of times before."
    roman "Well, let me tell you that, folks: you just don't know what you're missing yet, because you haven't tried it!"
    roman " Fair warning: the old new stuff just ain't going to be what it ever was like once you've had a proper taste."
    "A few in the audience laugh. Some start whispering to their tablemates. That's good. That's real good."
    "I'm getting to them."
    roman "But those are all future problems, right? For now, you want to try the real deal, yeah?"
    roman "So just for you, just tonight, Arcady's got all the greatest brands and labels, the prices are great, and we've got all the special deals you could shake your glass at."
    roman "So sit back, relax, and enjoy the true, proper Arcady experience the way you never have, but should have."
    "I instinctively give a small bow--even though, now that I think about it, I probably shouldn't have had to--and climb back down the stairs, feeling like I've just come back from war."
    "Passing a hand over the bridge of my nose and through my hair, I now know what I need."
    "I need a drink."
    "It's okay, though. I think we got a few of those lying around."
    show bg_black with Dissolve(0.75)
    hide bg_black with Dissolve(0.75)
    "That's more like it."
    "Standing in a shadowy corner, just out of sight of the customers but close enough to observe, my break has just begun holding a cold, sloshing glass of the old gold in my hand."
    "This is the life."
    "The tunes are all proper jazzy, like I've picked them, and the whiskey goes down the throat like liquid flames, with a perfect, smoky aftertaste."
    "So smooth you practically couldn't tell that it's met the tongue."
    "With everything in place, the time has come for my final mission for tonight. The final piece of the puzzle that will make it all come together in a glorious, perfect picture."
    "And I've now found just the person I needed."
    roman "So, how do you like the evening so far?"
    "Eris' head pans like a security camera from one side of the club to another, then back towards me. Her shoulders pull up indignantly against the wall."
    show eris p1 e1 at centered
    eris "Hm."
    eris "It {i}is{/i} pretty lively. I'll give you that."
    eris "Livelier than I'd imagined it'd be, that's for sure."
    eris p2 e7 "Then again, I did imagine half the club empty and the other half comprised of you. It wasn't too hard to top that."
    roman "Seems you've been underestimating me the whole while after all. What a shock."
    roman "World's full of nice surprises, isn't it? Maybe next time you'll think twice before challenging me."
    eris "Wow. Someone's full of themselves."
    roman "Sorry, I'm just savoring your grumpiness. Goes fantastic with the bourbon."
    show eris p2 e5 at centered
    "Eris rolls her eyes."
    roman "Look, we can just put all that behind us now, right? Here, have some of this. To show that I'm a dignified winner and all."
    # TODO: note: I don't know where we want the CGs to be yet, but if we're going to have those I think we should absolutely consider using a CG for the following part. Read it over and tell me if you think it's worth one.
    play audio whiskey_pour
    "I pick the bottle I've just used off of the counter and fill up another glass. If anyone's going to need that by the end of the night, it's going to be Eris."
    eris p1 e2 "Seriously? Wow, that's... that's actually --"
    play audio whiskey_ice
    roman "--and there you go. Just perfect."
    play audio whiskey_toast
    roman "Cheers."
    eris "..."
    eris "Uh, Roman?"
    eris "The hell did you just put in my glass?"
    roman "What, those?"
    eris "Yeah. Those things you just put in my glass which {i}obviously aren't ice.{/i}."
    "I chuckle."
    roman "{i}Those{/i}, my dear Eris, are pebbles. Special pebbles."
    eris p1 e6 "Pebbles?"
    roman "Pebbles."
    eris "Pebbles. You put pebbles in my whiskey."
    roman "Indeed I did. Special, drinking pebbles"
    eris p2 e5 "W--"
    eris "Why would you--"
    eris "Why would you put special pebbles in whiskey? Do you have pebbles in your whiskey right now?"
    "I take another swig off my own, letting the drink slosh silently in place for a while before setting it down on the table."
    "Makes sense, ultimately. Didn't really think anyone here would know that much, last of all Eris."
    roman "It's just how the real connoisseurs do it, you know? Thought I'd give you an opportunity to try, what with the fact you're going to lose our bet and all. I'm magnanimous like that."
    eris p2 e7 "Okay. Sure. Real Mother Theresa here."
    eris "So, assuming that I'm a complete whiskey sprog, mind explaining to me why the hell the connoisseurs are drinking it with pebbles?"
    roman "Absolutely. It's actually quite simple: normally, you'd use ice cubes, right? But you put ice in your whiskey, by the time you get around to drinking it half of it's melted, and it's diluted your drink. No good."
    roman "So you use those special pebbles--you put them in the freezer for a while--then by the time you want to start drinking, you can just plop a cold one in, and it's like ice that just never melts."
    roman "You could say it's a real 'whiskey on the rocks', huh?"
    eris p1 e6 "I'm going to just let that slide without comment, since you're obviously drunk."
    roman "Drunk? The night's still young, and I'm doing fine. And let me tell you: those pebbles are some classy stuff. You should be thanking me for that. I paid good money for them."
    show eris p1 e2 at centered
    "Eris' eyes open wide like glass bottoms. "
    eris "You {i}what{/i}?"
    roman "I paid for them. Good money. Special pebbles don't come cheap, but after I've won I'm sure I'll be having my investment return tenfold."
    show eris p1 e10 at centered
    "Eris begins to laugh. It starts off slowly, around her abdomen, then it slowly rumbles up all the way to her face and she has to set the glass down so it won't spill."
    "I got to say, it's kind of insulting, in context."
    eris "You paid {i}money{/i} for {i}pebbles{/i}?"
    roman "{i}Special{/i} pebbles."
    eris "Roman, this is some literal stone soup shit here. These are {i}rocks{/i}. It's basically condensed {i}dirt{/i}."
    roman "Okay, two things: one, you can't--and this is important--you can't put a price tag on an {i}experience{/i}. And this is what it is, Eris: this is an experience."
    roman "Second: I'm pretty sure those pebbles have, like, a special atomic structure, or a chemical composition or... You know. Something like that. Not just any pebble would do."
    "Eris just continues laughing."
    eris " You know what I do when I need a pebble? If for whatever weird reason I decide that I need a pebble? I got outside and grab one. Off the ground. Where the pebbles live."
    roman "Really? You do that? Because I thought you just--whooosh!"
    "I wiggle a couple fingers in the air as a demonstration--"
    roman "Just input the command in and conjure one, eh? Pretend there's a pebble."
    eris p1 e6 "Rich, coming from someone who literally had someone else convince you to {i}pay{/i} for these. What do you think the net profit on that was? Do you think it was about equal to however much you paid for it?"
    "I furrow my brow."
    roman "What, you'd pick a pebble off the ground to put in your drink? Super unhygienic. You don't know where it's been."
    eris p1 e6 "Sure. There's that."
    eris "I'm just saying--don't act all cocky just yet, yeah?"
    eris "For all we know, people might just be rushing in for a drink to avoid the hot air."
    roman "Or it might just be that it's been ages since any club around here's offered such an authentic experience and they can't wait to get a taste of some of the the good stuff."
    eris p1 e1 "I suppose. Guess we'll have to wait until my turn is finished. {i}Then{/i} we can be all scientific and compare the results."
    roman "Now that I'd like to see. Can't {i}wait{/i} to find out what kind of overhyped new gizmo you're all crazy ready to wire-up in here."
    eris p2 e5 "Alright, don't be a dick. I'm drinking your whiskey and all, aren't I?"
    eris p1 e6 "And for the record, it's not bad. So you do have that going for you."
    roman "Thanks. I suppose you do have a point"
    roman "Guess I'll save the gloating for {i}after{/i} I officially humiliate you."
    "Eris huffs, her elbows twitching in a way that says she'd cross her arms all over again, if they weren't already."
    show eris p1 e6 at centered
    "Her face lights up afterwards, though. A little smile sneaks up from the shadows."
    eris "You know what the great thing is about you being all smug like that? That when I beat you, you're just going to look {i}that{/i} much sillier."
    eris "I think I could even get Parker to laugh at you. Like, not even give one of those chuckles of his, you know? Actually {i}laugh{/i}, laugh. Belly rumbling like that."
    eris "Oh!"
    eris "Speak of the devil~"
    "Eris waves for me to look over back."
    "Sure enough, Parker seems to have take his break and is coming our way."
    roman "How's it going, Parker? Greatest night we've had in a while, right?"
    show eris p1 e6 at center_left
    show parker p1 e4 at center_right
    parker "Heard you people were talking money. You know how my ears work."
    "He turns towards Eris."
    parker "Enjoying your drink?" 
    eris "It's cool. Very different from the usual, if nothing else."
    roman "Who'd have thought good whiskey wouldn't be like a kiwi mojito..."
    show eris p1 e1 at center_left
    "Eris pulls her tongue out at me. Under the influence of the whiskey, I return the gesture."
    "All Parker can do is look at us both as if he's suddenly rethinking his life choices."
    parker "..."
    parker "In any case, would you mind giving us some space for a few minutes, Eris? I have something I'd like to talk over with Roman."
    eris "Sure. Be over there if you need me."
    show eris p1 e1 at transform_hide
    hide eris
    show parker p1 e4 at centered
    "Eris leaves her half empty glass on the table and struts off towards the customers, leaving me all by myself in my corner with Parker."
    roman "So? What is it?"
    parker "Roman, I think the two of us need to talk a bit about this idea of yours."
    roman "What? You mean this evening? It's going great, isn't it?"
    show parker p1 e2 at centered
    "Parker takes a deep, slow breath. His eyes are filled with what looks to be resignation."
    parker "Look."
    roman "What? What is it?"
    parker "I know that this... means... to you. I don't know if I would say that it means 'a lot', because honestly, from where I'm standing, it looks like you've made this bet with Eris over bullshit."
    parker "No offense."
    roman "Not enough taken to matter."
    parker "Good."
    parker "My point is, I know that you're excited and you care a lot for this evening, but..."
    show parker p1 e2 at centered
    parker "How should I say it? Have you looked around yourself recently?"
    roman "Huh? Of course I did. I planned this whole event, you know I'll be on top of things."
    parker "Okay. And what do you see?"
    "I try reading it in Parker's eyes if he's joking, or if he means that in some kind of tricky way."
    "He's as inscrutable as he'd ever wanted to be."
    "I look around again, just to check."
    "It looks like everyone's having a good time. People are drinking. People are talking. People are over by the pool table. It all looks fine to me."
    roman "I see... a great night. Isn't it?"
    show parker p1 e1 at centered
    "Parker pinches the bridge of his nose in what's beginning to look ominously like impatience."
    parker "What are people doing?"
    roman "What do you mean? They're drinking, they're having fun, they're--"
    parker "Right. Okay. Let's stop there. People are drinking, you say? Can you tell me what?"
    roman "Well, it {i}is{/i}, not to stress this too much, a whiskey tasting evening, so I'd say whiskey, no?"
    "Parker stands silently in front of me, eyes boring into my very soul."
    parker "Among other things."
    roman "Well, obviously. This is still a club, they're free to order whatever they like. It all averages out in the end, though."
    roman "I {i}personally{/i} served nine customers this night's special whiskey already. And I bet you and Eris did some, too."
    roman "Besides, we've only just started. Once people have gotten comfortable, I'm sure they'll--"
    parker "Roman, listen to me."
    parker "You said yourself that this is my specialty, didn't you?"
    parker "And you know what? You're right. I'm a bartender. I know a thing or two about drinks."
    parker "For example, I have a general idea of how much drinks tend to cost."
    parker "Now, I don't know what kind of 'authentic', 'cool' boutique place you got all that whiskey in, but that doesn't change the fact whiskey tends to have a certain price."
    parker "As it happens, I'm {i}also{/i} the guy paying your salary."
    parker "So unless you really {i}are{/i} moonlighting as a drug dealer behind my back on top of doing that job, I'm going to hazard a guess and say you haven't spent less that a month's wages on the booze for today."
    roman "Yeah, but this was all to show Eris--"
    parker "Roman! This is {i}a lot{/i} of money to throw at a stupid, childish bet. It's {i}way, way{/i} too much money."
    roman "But it'll pay itself back! People are buying the whiskey, and we're making a profit off of each glass!"
    parker "Off of each glass, yes, but you bought enough whiskey to fill a bathtub!"
    show parker p1 e2 at centered
    "Parker raises a finger towards me that looks almost accusatory."
    parker "To you, this whiskey is 'old-school' and 'hip' and whatever it you're thinking. That's fine."
    parker "To most of these people, though?"
    parker "This is going to sound terrible, but as a bartender, I can tell you for a fact that to most of those people, your expensive, gold label, real-deal whiskey is {i}just another drink{/i}."
    parker "It's tasty and it's nice, but you know what else is? Eris' awful kiwi mojitos. Or Mexican corn beer, for that matter."
    roman "W--come on, it can't be that--"
    parker "Please don't argue with me. You know that I hate sounding like that."
    parker "I'm just telling you how things are. As the guy who's getting all of the tabs."
    roman "And?"
    parker "And as I've said, people aren't buying your special whiskey. Not anymore than they buy anything else, anyway."
    parker "So as I see it, it's {i}not{/i} going to pay back for itself. Not even remotely. This isn't even mentioning how very unlikely it is that this event will draw in more people."
    "Parker sighs."
    parker "I really care about you, guy. I'm only doing this because I do."
    roman "...doing what?"
    parker "Telling you this: your special whiskey night? I think we should call it off. Early as possible."
    roman "Call it off?! But I've already--"
    parker "Third time, Roman: this isn't up for discussion. Arcady is still my club, you are still my employee, and my decision about this is final."
    show parker p1 e5 at centered
    parker "I like your spirit. I like your attitude. I like how you...talk about things most people nowadays wouldn't care less about."
    parker "And part of that means I like you enough to see you making a very stupid decision that you're going to regret ten days from now, just because you're currently hyper-focused on something Eris told you three days ago."
    "I lay the glass down. Maybe it's the alcohol, but..."
    "It really feels like I've just had all the wind knocked out of me."
    roman "How about the pool table, though?"
    parker "Yeah, about that..."
    parker "I want you to look over it again and tell me what you see."
    roman "Can we... can we not do this again?"
    parker "Alright. Then I'll tell you what I'm seeing: I'm seeing people checking out the huge-ass 3D printed monstrosity you've tucked right in the middle of my club in place of three tables I could put customers in."
    parker "I'm seeing them giggling to themselves because they never saw one in real life, then I'm seeing them picking a cue up, fumbling with it for two minutes trying to hit a ball, and then going back to their tables to laugh it off with a beer."
    roman "Don't be so harsh. It can't be that bad. I've seen them myself. It's fine."
    parker "Listen: I'm saying this as a friend."
    parker "When someone wants to see something, odds are they're going to see it."
    parker "And I think that right now, you're seeing what you want to see. You have been all night."
    parker "People aren't having fun with that pool table. All that thing embodies is a distraction."
    roman "...that's just because they just don't understand real pool. It's not like AR, it's got weight, it's got--"
    parker "It's got a lot of stuff these people just don't {i}care about{/i}."
    parker p1 e4 "You've tried your best and it's great. But you've gone overboard."
    parker "This has to end. Now."
    "Parker leans against the wall, looking about an eighth as tired as I'm feeling all of a sudden."
    "It's astonishing how quiet it can feel inside a club full of people when you're like this."
    "I open after a tiny eternity."
    roman "What do you want me to do?"
    parker p1 e1 "First of all, don't worry about telling people about this. I'll handle this, okay?"
    parker "We let the customers have another order of whiskey if they want to. Close the tap on that slowly."
    parker "Then, we're going to take every bottle we haven't had to open yet--and lucky for you that's the vast, vast majority of them--and we're going to put it out in the back."
    parker "What I want you to do is, as soon as tomorrow morning, pack them back into the crates you got them in and return them to the store. See if you can get a refund."
    parker "If you're having any trouble with that, call me. I'll do my very best to make sure that you get as much of your money back as you can."
    "Without even noticing it, I've gone from looking ahead at the crowd to staring at my own feet."
    "I can't even see them, in the dark. It's pretty pointless."
    "I feel like I'm a high school kid all over again, only this time {i}actually{/i} being scolded for fucking up. "
    parker "I'm also going to have you take apart that pool table. It's a serious eyesore."
    roman "...fine. I'll get right on it."
    show parker at embiggen
    "Awkwardly, with surprising tenderness, Parker moves closer to me."
    "I'm scared that he's going to hug me, but thankfully, all he does is rest a hand on my shoulder."
    "Given the circumstances, it's actually quite a comfortable if bitter sentiment."
    parker "Great. You know where to find me if you need anything."
    show parker p1 e1 at transform_hide
    hide parker
    "He starts walking away, but after a second thought turns back towards me."
    show parker p1 e5 at centered
    parker "By the way--"
    "His head is already turning away right before leaving--"
    parker "It is pretty good whiskey, you know?"
    parker "I think I might save myself a bottle. I'll even pay you for it."
    roman "Huh."
    roman "Thanks."
    show parker p1 e5 at transform_hide
    hide parker
    "Parker disappears into the crowd. The next time I spot him, he's right back in his spot behind the counter, looking busy and dignified like he always does."
    "Now's my turn to sigh."
    show eris p3 e9 at centered
    eris "Everything alright? What was all that about?"
    roman "Nothing. He just wanted to buy one of those bottle from me. Said the whiskey was really good."
    eris "Oh."
    eris "Alright."
    "Glancing aside, I can see her eyes trying to follow mine in the dim light, her expression shifting imperceptibly between bemusement, intrigue, then--"
    "Jesus, this is awful."
    "Concern."
    eris "Well..."
    show eris p3 e8 at centered
    "She shifts uncomfortably in her place, almost as if she needs to go to the bathroom."
    eris "Nice evening, huh?"
    roman "Yeah."
    eris "Well... I'll be over there if you--"
    roman "Right. Thanks. {i}Thanks a lot{/i}."
    show eris p1 e1 at transform_hide
    hide eris
    "With a forced smile and a raised thumb, she disappears into the lighting."
    "Leaving me all by myself in the corner. For real, this time."
    roman "Might as well get started on that pool table..."
    show bg_black with Dissolve(1.5)
    return