label A1_04:
    scene bg_club_2_before_work with Dissolve(0.5)
    $ queue_music(music_four1)
    $ crossfade_music(0.0, 1.0, 0)
    "It was almost humiliating to come back to work today. Last night was a disaster of unbelievable proportions." 
    "It has often been said that 'no plan survives contact with the enemy,' but my idea did more than just {i}not{/i} survive. It was crushed. Demolished. Burned to the ground like it had killed someone's loved one."
    "It taught me what Parker's like when angry, a lesson I could've done without."
    "After last night's hilarious little mess-up, I've already braced myself to see either of two things as soon as I arrived: Parker's disappointed frown... or Eris's victorious grin."
    "I'd sooner jump off a cliff in a tutu than let her get under my skin and rub this in my face."
    "{i}Our 'competition' has barely begun{/i}, I've tried to tell myself.{i}I'll have the last laugh all the same.{/ i}"
    "I'd have other ideas eventually. Better ones, even."
    "But... after all that, I've realized it's all a bit pointless in the end."
    "I'll just end up where I started, and just accumulate another embarrassment."
    $ crossfade_music(1.0, 0.0, 5.0)
    "So screw the bet, if Eris wants to gloat then I can tell her right where to shove it." 
    "And besides... there's still some solace in returning back to ARTech."
    "A wicked smile crosses my face as I take in Arcady's lobby and prepare for the day."
    "{i}I can always quit again.{/i}"
    parker "You're in a strange mood, Roman."
    parker "Excited to see what Eris has in store for us this evening?"
    show parker p1 e1 at centered
    "Parker approaches me from behind me, though he's more so looking over the club than at me."
    "His tone is an inscrutable mask, but since it's a palpable improvement from his disappointment last night I'll take that as a blessing."
    "I try and think over something witty in my head, though as I'm scanning across the room... something {i}very{/i} important occurs to me."
    roman "Where's Eris?"
    "I thought she'd be the first to confront me stepping into work... but she's nowhere to be seen."
    parker "I thought you'd end up telling me."
    parker "She's actually now late checking in to work."
    roman "{i}What!?{/i}"
    "He turns his attention now towards me, though I wasn't expecting to raise my voice that loud."
    roman "..."
    roman "Sorry."
    roman "I've just never seen her late to anything before."
    roman "She's always been the first to arrive, last to leave kind of person you know?"
    "Parker gives me a knowing nod. He knows."
    "I'd like to think that this could be a blessing, that maybe Eris decided to back out at last minute."
    "That for once she could admit to not being able to do something."
    parker p1 e5 "It is quite curious, don't you think?"
    "No."
    "Accounting for Parker's smile, dreadful is how I'd word this atmosphere."
    "All I can do is sullenly nod, and wait to see if he's going to say anymore, but-"
    show parker p1 e5 at transform_hide
    hide parker
    "He's already walking away." 
    "That was it, the extent of our conversation."
    "Even as the jazz music supposedly fills the room, this tense air is suddenly assaulting my senses"
    "My hands feel wet, tongue tastes dry, and a newfound hollowness is rising from within me."
    "I can always quit ARTech but... Eris will always hold this moment against me."
    "It's something that I'd never be able to escape from, no matter how much I try and distract myself."
    "{i}Great band we have today, huh Roman?{/i}"
    "{i}I heard they came from the next city over, a place that's almost like a cultural underground for authentic jazz music.{/i}"
    "{i}And it's not too far at all... but right now it might as well be light years away.{/i}" 
    "Just how long is it going to be until I get there?"
    "A new start. A new life."
    "..."
    "It's fine, I understand."
    "I was in the wrong buying crates of expensive whiskey, I was just too carried away with the big scheme in my head"
    "I sweep the club with a glance."
    "Absolutely no traces of the amenities I introduced yesterday for my big plan remained. The whiskey's been returned, the billiard table hauled off."
    "...I could've planned it better."
    "People say it's good to be able to acknowledge mistakes when they happen, though it's not surprising just to see just how hard that actually is."
    "I mean, what the hell else is a jazz club without billiards?"
    "At the doorway I catch a pair of patrons enters: a tall, middle aged woman in a long black dress and a pudgy man in an ill-fitting tux, linked arm in arm."
    "That'd be my cue, then. Back to work."
    "And right away."
    "I hurry over to the couple, trying to find some comfort in the monotony of serving."
    "I don't know what's taking Eris so long, but I try and cherish some calm before the storm." 
    "For as long as it'll hold."
    show bg_black with Dissolve(0.75)
    hide bg_black with Dissolve(0.75)
    show eris p2 e7 at centered
    "...It didn't hold for long."
    "I was barely finished serving the middle-aged pair when Eris finally strides through the doors, wearing the exact kind of triumphant smirk I had expected her to be sporting."
    eris p2 e4  "I didn't think you'd still be able to come here after yesterday, Roman. Takes some real audacity, after a disaster like that."
    eris p2 e7 "Maybe if only you'd had that tenacity back at ARTech, you wouldn't have needed to leave."
    "I simply nod as I turn my back to head for the counter. {i}You can always just quit again{/i}, I keep telling myself." 
    show eris p2 e3 at centered
    "She eyes me with suspicion in response. It seems I didn't give her the reaction she wanted out of me."
    eris "But really though, when you {i}really{/i} think about it, whiskey-tasting? That's really just a bit out-of-touch in the end."
    eris "I might be the new guy, but even I realize how important it is to take account of the customer's taste rather than just your own."
    "I give her no ground, simply nodding again and continue to silently clean the table in front of me."
    "All I can do now is focus on work."
    eris "..."
    eris "...well, I have something to discuss with Parker."
    eris "I'll talk with you later."
    show eris p2 e3 at transform_hide
    hide eris
    roman "...right."
    "I can't help but watch her as she practically glides across the room, over to the bar counter where Parker is polishing a wine glass."
    "Today of all days she's in the highest spirits that I've ever seen her. Perhaps she's come up with the best idea imaginable."
    "Or at least, something she thinks is one."
    "She chats with Parker a bit, probably to explain why she was late, before she darts off quickly to the other end of the club."
    "Before I could give it more thought than it warrants, another customer calls out, waving their hand to get my attention."
    "There are a bit more customers today, thankfully, which makes it easier than usual to distract myself. Two more acts follow the band that had played earlier, both of which also came from outside the city."
    "And before I know it I'm back to my usual rhythm, one that's weirdly assuring to fall back into." 
    "The night wrapped up without any further complications--a bit of respite that I embraced wholeheartedly while I could."
    show bg_black with Dissolve(0.75)
    scene bg_club_1_off_work with Dissolve(0.75)
    $ crossfade_music(0.0, 1.0, 5.0)
    show parker p1 e5 at center_right
    show eris p1 e6 at center_left
    "After work Parker calls the entire staff to sit in the main room of Arcady."
    parker "Good work so far, everyone. Do take a seat."
    "Parker takes his seat on a nearby couch, now sipping a cup of tea. Eris and I sit as far apart as we possibly can."
    parker "Earlier, Eris asked me to have us meet up here. I believe she has something to say?"
    "Eris takes this as her cue to jump up from her seat. She's got a glimmer in her eye; my guess is that she's ready to present her idea."
    eris "So, everyone, you may have noticed I was late today..."
    "She takes out her phone and places it gently on the table."
    parker p1 e3 "What's this? New phone?"
    eris "Not at all! It's what's on the screen that I'm about to present to you."
    show parker p1 e1 at center_right
    "She does a quick double-tap, showing us an elaborate setup of electronics and assorted components."
    eris p1 e1 "I couldn't help but notice how... rundown the club's current AR platform is when it comes to catering our customer's virtual interface."
    "{i}My{/i} proposal was to upgrade it with a new program that I've been developing over at ARTech, something that'll make AR in this club far more efficient than ever before!"
    "You don't even need to worry about cost - these are all my components that I've had approved to bring over here. Consider it a 'donation' of sorts from yours truly."
    show parker p1 e3 at center_right
    "Parker's eyebrows shoot up at the mention of 'donation.'"
    parker "Eris, that's... very generous of you. But this won't change anything too distract with our club's system, right?"
    parker "It's not like I've ever gotten any complaints about the current club's interface."
    roman "Will it even work?"
    "I can't help but chime in, eyeing this plan with more disdain than ever before."
    "Of course leave it to Eris to make club performance about her own AR obsession."
    eris p2 e4 "I can upgrade the platform after we close up tonight, and I can assure you all we'll have the best performances in the city by tomorrow!"
    parker p1 e1 "..."
    parker "All right, I'll let you handle the upgrade."
    parker "Feel free to take your time, though--it's poor form to have exhausted-looking employees."
    eris p1 e6 "Okay! I promise you, you're all going to {i}love{/i} this!"
    show parker p1 e1 at transform_hide
    hide parker
    "Looking at the plans she has presented, I can tell that she put a lot of time and effort into this, same with how I set up my whiskey-tasting night."
    "The more I look at it though... I think there's a problem with her approach."
    eris p1 e1 "Anything on your mind, Roman?"
    roman "You sure these are all compatible? Did you check the hardware we have here prior to this?"
    eris p2 e5 "Of course I did! Otherwise I wouldn't have gone out of my way to bring all the stuff here today."
    "Ah, a reason why she was so late perhaps?"
    "I don't doubt she assumes to have things under control. Still... perhaps it really was far too premature to be worried over this."
    roman "Alright, just be sure to holler if you end up setting something on fire."
    eris p1 e1 "Hmph."
    show eris p1 e1 at transform_hide
    hide eris
    "She dismisses me with a wave and heads off to take care of cleaning up tables."
    show bg_black with Dissolve(0.75)
    hide bg_black with Dissolve(0.75)
    $ crossfade_music(1.0, 0.0, 5.0)
    "Most of the other staff have already gone home for the night."
    "I can see Eris already dumbly eager to get started on overtime, watching her furiously scrub the floors clean as she runs back and forth on Arcady's main floor."
    show eris p1 e1 at centered
    roman "Wow, Eris, if you were this fast every day we'd have no trouble closing on time."
    eris p2 e5 "This is always how I work."
    roman "Whatever. You ready to start on your little project soon? Parker's already about ready to head out."
    eris p1 e1 "Sure, in a minute. I just need to bring the new electronics in through the side entrance, and after that it'll be a cinch to set everything up."
    roman "Try not to break anything then."
    show eris p1 e1 at transform_hide
    hide eris
    "I find Parker in the back, writing on a few miscellaneous document scatter across the bar counter."
    "He looks up as I approach."
    show parker p1 e1 at centered
    parker "Ah, still sticking around then?"
    roman "Yeah. Eris says she's confident in setting things up for the club, but I just want to make sure she doesn't end up messing anything up."
    parker "Haha, it's OK to be curious Roman."
    roman "There's no way that I am Parker."
    parker "Hm, alright then. I'll still be sticking around to keep an eye on her too. I have a few bits of paperwork to do in the back while she works."
    roman "She said she's have things ready by tomorrow morning. You're not worried this'll take too long?"
    parker "Will it?"
    roman "It shouldn't..."
    show parker p1 e1 at transform_hide
    hide parker
    "I turn back to check on Eris, and already see that she's pulling in equipment to hook up to Arcady's current AR platform."
    "There's a part of me that obviously doesn't want her to succeed, but seeing all the passion that she's currently putting into this..."
    "There's another strange part that wants to see her do well."
    "It's the first time that I've really seen her smile in my time of knowing her."
    show parker p1 e1 at centered
    parker "Well, let me know how things go if you decide to stick around."
    roman "...Sure."
    show parker p1 e1 at transform_hide
    hide parker
    "Parker heads back and I'm left watching someone that should in every sense be my enemy set up their means to beat me."
    "True to my expectations, things really don't take that long to set up."
    show eris p3 e9 at centered
    eris p3 e9 "Okay, that's installed, just gotta run a test real quick..."
    "She looks up and catches sight of me by the bar, almost as if she's just realized that I was still here."
    eris p1 e1 "Oh, Roman."
    eris p1 e6 "Wanna watch me win our competition that bad, huh?"
    roman "Don't be full of yourself Eris, I'm here because Parker asked me to watch you."
    eris p1 e10 "Too bad, I've already hit the swit--"
    $ queue_music(music_four2)
    eris p1 e1 "..."
    eris p2 e5 "..."
    "Something stops Eris from continuing her gloating, her fingers madly tapping and swiping at the screen."
    eris p2 e5 "Shit. {i}Shit!{/i}"
    roman "Hm? What's wrong?"
    "Eris ignores me, too busy trying to analyze the device's screen."
    show eris p3 e8 at centered
    "Eventually, she turns to me, a look of horror crossing her eyes."
    eris "...Look."
    "She hands over the tablet, which tells me everything I need to know."
    "ERROR 11: DEVICE NOT SUPPORTED."
    "The shiny new tech she's carrying is {i}too{/i} new, it seems. Even though Parker's platform would only be a few years behind the latest, it's no longer enough to catch up with this year's model."
    "I can't help but chuckle over the thought."
    roman "And you said you checked for compatibility?"
    eris p2 e5 "I did!"
    eris "I checked {i}everything{/i}, the platform is supposed to run on AOS version 3.17."
    roman "Well, let me check."
    "It takes a few moments... but sure enough, the version number is correct."
    roman "So what's the minimum system requirements for your equipment?"
    eris p2 e3 "I was {i}told{/i} that they were compatible all the way back to version 3.0!"
    roman "Well, as I'm sure you now know, they're not."
    roman "You know, at least according to this error message."
    eris p2 e5 "Dammit. {i}Shit!{/i}"
    "She angrily grabs a hold of her hair, spewing out a string of curses and muttering under her breath."
    eris "All the devs said it would work this way." 
    eris "I spent all this time making an ass of myself earlier today. Everyone will come in tomorrow and see that {i}nothing{/i} has changed."
    eris "And I had the gall to boast to everyone."
    eris "{i}Goddammit!!!{/i}"
    "She yells that last curse, actually startling me in the process."
    "I hear the sound of running footsteps, and catch the sight of Parker rushing towards us."
    show eris p2 e5 at center_left
    show parker p1 e3 at center_right
    parker "What the hell's going on out here?"
    parker "Is everything OK?"
    roman "Well... yeah, it's just that--"
    eris p3 e8 "I'm sorry Parker."
    eris "Those changes might take a while longer."
    "The once tense attitude on our boss instantly evaporates, now replaced with exasperation."
    eris "But I can stay late and try and fix the system! If I can have a little more time I assure you--"
    $ crossfade_music(0.0, 1.0, 10)
    parker "{i}Eris.{/i}"
    parker "I'm going to need you to go home."
    parker "I mean Jesus, I thought someone was actually hurt out here!"
    "Any semblance of comfort crumbles away from her into shameful embarrassment."
    eris "N-no..."
    eris "It's just..."
    eris "I..."
    "A stillness extends over all three of us, only broken by Eris hanging her head in defeat."
    eris "I'm sorry."
    eris "I'll be heading home now."
    show eris p3 e8 at transform_hide
    hide eris
    "She sulks out the door, and Parker now turns my way perplexed."
    parker p1 e1 "Roman, is everything OK?"
    "I explain to him about the platform's version incompatibility, and the torrent of curses that came afterward."
    parker "I see."
    parker "All because of this huh?"
    roman "Yeah..."
    "That's just always how she's been."
    parker "I'll try and talk things over during her next shift. For now..."
    parker "Mind helping me lock up?"
    roman "Sure thing."
    show parker p1 e1 at transform_hide
    hide parker
	stop dynamic_1 fadeout 5.0
	stop dynamic_2 fadeout 5.0
    "Tonight was a disaster, one that I should ultimately feel happy about."
    "Eris's plan was crushed. Demolished. Burned to the ground like it had killed someone's loved one."
    "I guess..."
    "...now we could call ourselves even."
    return